"""
PostgreSQL store for the server-side video cache.

When caching is enabled, playing an episode kicks off a background job that
downloads the *complete* stream to a NAS share (remuxed to mp4 — see
``cache_engine.downloader``) and records a row here. On the next play the
``CacheScraper`` surfaces that file as a first-class source, labelled with the
NAS target's admin-given **name** and the original audio/subtitle language.

Three tables:

  * ``cache_targets``    — the NAS directories the operator exposes for caching,
                           each with a display *name* the cached source is shown
                           under (a NAS share / Docker bind-mount, e.g.
                           ``-v /nas/cache:/crimson/cache`` -> register
                           ``/crimson/cache``). Mirrors local_engine's
                           ``local_media_sources``.
  * ``cache_settings``   — a single-row global master switch (caching on/off).
  * ``cached_episodes``  — one row per cached (tmdb, season, episode, language).
                           Carries the download lifecycle (pending -> downloading
                           -> ready / failed) and where the file landed.

Mirrors local_engine.db / account_engine.db: plain pooled psycopg calls borrowing
from the shared pool (db_pool), driven from api.py's async handlers via
``run_in_threadpool``. Volumes are tiny.
"""

from __future__ import annotations

import os
import time
from datetime import datetime, timezone
from typing import List, Optional

from db_pool import get_connection, lock_schema_init

_TARGET_COLS = "id, name, path, enabled, created_at"
_EP_COLS = (
    "id, target_id, tmdb_id, media_type, season_number, episode_number, anilist_id, "
    "language, source_origin, rel_path, container, file_size, status, error, "
    "created_at, updated_at"
)

# Lifecycle states for a cached_episodes row.
STATUS_PENDING = "pending"
STATUS_DOWNLOADING = "downloading"
STATUS_READY = "ready"
STATUS_FAILED = "failed"
_ACTIVE_STATES = (STATUS_PENDING, STATUS_DOWNLOADING, STATUS_READY)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class CacheStore:
    """Data layer for the video-cache tables."""

    # The enabled-targets list is read on every scrape / download-trigger / proxy
    # request, so it's cached process-wide for a few seconds (same pattern as
    # LocalSourceStore). Shared at class level; any write invalidates via _bump().
    _targets_cache: Optional[List[dict]] = None
    _targets_cache_at: float = 0.0
    _TARGETS_TTL = 5.0

    # ----------------------------------------------------------------- schema
    def init_db(self) -> None:
        """Create the schema (idempotent)."""
        with get_connection() as conn:
            lock_schema_init(conn)  # serialize DDL across replicas (see db_pool)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cache_targets (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name       TEXT NOT NULL,
                    path       TEXT NOT NULL UNIQUE,
                    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TEXT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cache_settings (
                    id         INTEGER PRIMARY KEY DEFAULT 1,
                    enabled    BOOLEAN NOT NULL DEFAULT FALSE,
                    updated_at TEXT NOT NULL,
                    CONSTRAINT cache_settings_singleton CHECK (id = 1)
                );
                """
            )
            conn.execute(
                """
                INSERT INTO cache_settings (id, enabled, updated_at)
                VALUES (1, FALSE, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                (_now_iso(),),
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cached_episodes (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    target_id      BIGINT NOT NULL REFERENCES cache_targets(id) ON DELETE CASCADE,
                    tmdb_id        BIGINT NOT NULL,
                    media_type     TEXT NOT NULL DEFAULT 'tv',
                    season_number  INTEGER NOT NULL,
                    episode_number INTEGER NOT NULL,
                    anilist_id     BIGINT,
                    language       TEXT NOT NULL DEFAULT '',
                    source_origin  TEXT NOT NULL DEFAULT '',
                    rel_path       TEXT NOT NULL,
                    container      TEXT NOT NULL DEFAULT 'mp4',
                    file_size      BIGINT,
                    status         TEXT NOT NULL DEFAULT 'pending',
                    error          TEXT,
                    created_at     TEXT NOT NULL,
                    updated_at     TEXT NOT NULL
                );
                """
            )
            # `media_type` ("tv" | "movie") namespaces the cache key. TMDB movie ids
            # and tv ids share one numeric space, so without it a cached movie would
            # collide with a same-id show. It's part of the UNIQUE key (and the lookup
            # index + claim_download's ON CONFLICT) below, and movies land under a
            # `movie-tmdb-<id>/` dir on the NAS (see cache_engine.fs.plan_rel_path).
            # Added via ALTER for DBs created before movie caching existed.
            conn.execute(
                "ALTER TABLE cached_episodes ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT 'tv'"
            )
            # The resolved, signed stream URL the cache-worker feeds ffmpeg. Stored
            # on the row so the download can run out-of-process (in the cache-worker
            # service) instead of in the api replica that handled /cache/confirm —
            # the DB row IS the job queue now. Added via ALTER for DBs created before
            # the worker split.
            conn.execute(
                "ALTER TABLE cached_episodes ADD COLUMN IF NOT EXISTS media_url TEXT"
            )
            # Drop the legacy TV-only UNIQUE (tmdb_id, season_number, episode_number,
            # language) constraint on DBs created before movie caching — the
            # media_type-aware unique index below replaces it. The old constraint's
            # name was auto-generated, so find it by its exact column set rather than
            # hardcoding a name.
            conn.execute(
                """
                DO $$
                DECLARE legacy_con TEXT;
                BEGIN
                    SELECT con.conname INTO legacy_con
                    FROM pg_constraint con
                    JOIN pg_class rel ON rel.oid = con.conrelid
                    WHERE rel.relname = 'cached_episodes' AND con.contype = 'u'
                      AND (
                        SELECT array_agg(att.attname::text ORDER BY att.attname::text)
                        FROM unnest(con.conkey) AS k
                        JOIN pg_attribute att
                          ON att.attrelid = con.conrelid AND att.attnum = k
                      ) = ARRAY['episode_number', 'language', 'season_number', 'tmdb_id']
                    LIMIT 1;
                    IF legacy_con IS NOT NULL THEN
                        EXECUTE 'ALTER TABLE cached_episodes DROP CONSTRAINT ' || quote_ident(legacy_con);
                    END IF;
                END $$;
                """
            )
            # The real cache key now — keyed by media_type first so movies and shows
            # with the same TMDB id never collide. claim_download's ON CONFLICT infers
            # this index by its column list.
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS cached_episodes_uniq "
                "ON cached_episodes (media_type, tmdb_id, season_number, episode_number, language)"
            )
            # Lookup index for the scraper's ready_for_episode (media_type-aware).
            # Replaces the pre-movie tmdb-only index of the same name.
            conn.execute("DROP INDEX IF EXISTS cached_episodes_lookup")
            conn.execute(
                "CREATE INDEX IF NOT EXISTS cached_episodes_lookup "
                "ON cached_episodes (media_type, tmdb_id, season_number, episode_number, status)"
            )

    # ----------------------------------------------------------- settings
    def get_enabled(self) -> bool:
        """Global master switch. Defaults to False (caching off) on a fresh DB."""
        try:
            with get_connection() as conn:
                row = conn.execute(
                    "SELECT enabled FROM cache_settings WHERE id = 1"
                ).fetchone()
            return bool(row["enabled"]) if row else False
        except Exception:
            return False

    def set_enabled(self, enabled: bool) -> bool:
        with get_connection() as conn:
            conn.execute(
                """
                INSERT INTO cache_settings (id, enabled, updated_at)
                VALUES (1, %s, %s)
                ON CONFLICT (id) DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = EXCLUDED.updated_at
                """,
                (enabled, _now_iso()),
            )
        return enabled

    # --------------------------------------------------------- target reads
    def list_targets(self) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_TARGET_COLS} FROM cache_targets ORDER BY created_at, id"
            ).fetchall()

    def get_target(self, target_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_TARGET_COLS} FROM cache_targets WHERE id = %s", (target_id,)
            ).fetchone()

    def enabled_targets(self) -> List[dict]:
        """All enabled targets (id/name/path), cached briefly. Used by the scraper,
        the download trigger and the /cache_proxy route on every request."""
        now = time.monotonic()
        cached = CacheStore._targets_cache
        if cached is not None and (now - CacheStore._targets_cache_at) < CacheStore._TARGETS_TTL:
            return cached
        try:
            with get_connection() as conn:
                rows = conn.execute(
                    f"SELECT {_TARGET_COLS} FROM cache_targets WHERE enabled = TRUE ORDER BY created_at, id"
                ).fetchall()
        except Exception:
            return cached or []
        CacheStore._targets_cache = rows
        CacheStore._targets_cache_at = now
        return rows

    # -------------------------------------------------------- target writes
    def add_target(self, name: str, path: str) -> dict:
        with get_connection() as conn:
            row = conn.execute(
                f"""
                INSERT INTO cache_targets (name, path, enabled, created_at)
                VALUES (%s, %s, TRUE, %s)
                RETURNING {_TARGET_COLS}
                """,
                (name, path, _now_iso()),
            ).fetchone()
        self._bump()
        return row

    def update_target(
        self, target_id: int, name: Optional[str] = None, enabled: Optional[bool] = None
    ) -> Optional[dict]:
        sets, vals = [], []
        if name is not None:
            sets.append("name = %s")
            vals.append(name)
        if enabled is not None:
            sets.append("enabled = %s")
            vals.append(enabled)
        if not sets:
            return self.get_target(target_id)
        vals.append(target_id)
        with get_connection() as conn:
            row = conn.execute(
                f"UPDATE cache_targets SET {', '.join(sets)} WHERE id = %s RETURNING {_TARGET_COLS}",
                tuple(vals),
            ).fetchone()
        self._bump()
        return row

    def delete_target(self, target_id: int) -> bool:
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM cache_targets WHERE id = %s RETURNING id", (target_id,)
            ).fetchone()
        self._bump()
        return row is not None

    # ----------------------------------------------------- cached-episode reads
    def ready_for_episode(
        self, tmdb_id: int, season_number: int, episode_number: int, media_type: str = "tv"
    ) -> List[dict]:
        """Ready cached files for an episode (or a movie, ``media_type="movie"`` with
        season/episode 0), joined to their (still-enabled) target so the scraper gets
        the display name. Disabled/removed targets drop out automatically (the JOIN on
        enabled targets), so toggling a target off instantly hides its cached sources.
        ``media_type`` keeps a movie from surfacing under a same-id show and vice
        versa."""
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {', '.join('ce.' + c for c in _EP_COLS.split(', '))},
                       ct.name AS target_name, ct.path AS target_path
                FROM cached_episodes ce
                JOIN cache_targets ct ON ct.id = ce.target_id AND ct.enabled = TRUE
                WHERE ce.media_type = %s AND ce.tmdb_id = %s AND ce.season_number = %s
                      AND ce.episode_number = %s AND ce.status = %s
                ORDER BY ce.language
                """,
                (media_type, tmdb_id, season_number, episode_number, STATUS_READY),
            ).fetchall()

    def get_episode(self, entry_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_EP_COLS} FROM cached_episodes WHERE id = %s", (entry_id,)
            ).fetchone()

    def list_episodes(
        self, status: Optional[str] = None, limit: int = 100, offset: int = 0
    ) -> List[dict]:
        where, params = "", []
        if status:
            where = "WHERE ce.status = %s"
            params.append(status)
        params.extend([limit, offset])
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {', '.join('ce.' + c for c in _EP_COLS.split(', '))},
                       ct.name AS target_name
                FROM cached_episodes ce
                LEFT JOIN cache_targets ct ON ct.id = ce.target_id
                {where}
                ORDER BY ce.updated_at DESC, ce.id DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()

    def count_episodes(self, status: Optional[str] = None) -> int:
        with get_connection() as conn:
            if status:
                row = conn.execute(
                    "SELECT COUNT(*) AS n FROM cached_episodes WHERE status = %s", (status,)
                ).fetchone()
            else:
                row = conn.execute("SELECT COUNT(*) AS n FROM cached_episodes").fetchone()
        return row["n"] if row else 0

    def stats(self) -> dict:
        """Aggregate counts + total bytes cached, for the dashboard."""
        out = {"ready": 0, "pending": 0, "downloading": 0, "failed": 0, "total_bytes": 0}
        try:
            with get_connection() as conn:
                for r in conn.execute(
                    "SELECT status, COUNT(*) AS n FROM cached_episodes GROUP BY status"
                ).fetchall():
                    out[r["status"]] = r["n"]
                row = conn.execute(
                    "SELECT COALESCE(SUM(file_size), 0) AS b FROM cached_episodes WHERE status = 'ready'"
                ).fetchone()
                out["total_bytes"] = int(row["b"]) if row else 0
        except Exception:
            pass
        return out

    # ---------------------------------------------------- cached-episode writes
    def claim_download(
        self,
        *,
        tmdb_id: int,
        media_type: str,
        season_number: int,
        episode_number: int,
        anilist_id: Optional[int],
        language: str,
        source_origin: str,
        target_id: int,
        rel_path: str,
        media_url: str,
        container: str = "mp4",
    ) -> Optional[dict]:
        """Atomically reserve a download slot for this (media_type,tmdb,season,episode,language).

        Inserts a ``pending`` row (carrying ``media_url`` — the resolved, signed
        stream the cache-worker will hand ffmpeg), or — if a row already exists but
        previously ``failed`` — flips it back to ``pending`` for a retry. Returns the
        row when THIS caller won the slot, or None when a ``pending``/``downloading``/
        ``ready`` row already exists (someone else owns it, possibly another replica —
        the shared unique constraint makes this the cross-replica dedup point).

        The caller does NOT download here; the dedicated cache-worker service polls
        for ``pending`` rows (see :meth:`fetch_pending` / :meth:`begin_download`)."""
        now = _now_iso()
        with get_connection() as conn:
            return conn.execute(
                f"""
                INSERT INTO cached_episodes
                    (target_id, tmdb_id, media_type, season_number, episode_number, anilist_id,
                     language, source_origin, rel_path, media_url, container, status, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (media_type, tmdb_id, season_number, episode_number, language)
                DO UPDATE SET
                    status = EXCLUDED.status,
                    target_id = EXCLUDED.target_id,
                    rel_path = EXCLUDED.rel_path,
                    media_url = EXCLUDED.media_url,
                    source_origin = EXCLUDED.source_origin,
                    anilist_id = EXCLUDED.anilist_id,
                    container = EXCLUDED.container,
                    error = NULL,
                    file_size = NULL,
                    updated_at = EXCLUDED.updated_at
                WHERE cached_episodes.status = %s
                RETURNING {_EP_COLS}
                """,
                (
                    target_id, tmdb_id, media_type, season_number, episode_number, anilist_id,
                    language, source_origin, rel_path, media_url, container, STATUS_PENDING, now, now,
                    STATUS_FAILED,
                ),
            ).fetchone()

    def fetch_pending(self, limit: int = 8) -> List[dict]:
        """Oldest ``pending`` download rows, joined to their still-enabled target so
        the worker knows the NAS root to write under and the URL to pull. Rows whose
        target was disabled/removed drop out via the JOIN (a later restart's
        ``reset_stale_jobs`` tidies them). The cache-worker's poll loop drains this."""
        with get_connection() as conn:
            return conn.execute(
                """
                SELECT ce.id, ce.tmdb_id, ce.media_type, ce.season_number, ce.episode_number,
                       ce.language, ce.source_origin, ce.rel_path, ce.media_url,
                       ct.path AS target_path
                FROM cached_episodes ce
                JOIN cache_targets ct ON ct.id = ce.target_id AND ct.enabled = TRUE
                WHERE ce.status = %s
                ORDER BY ce.created_at, ce.id
                LIMIT %s
                """,
                (STATUS_PENDING, limit),
            ).fetchall()

    def begin_download(self, entry_id: int) -> bool:
        """Atomically transition a row ``pending`` -> ``downloading``. Returns True
        if THIS caller won it (it was still pending), False if another worker/slot
        already claimed it. This is the cross-worker claim point now that downloads
        run in the cache-worker service, separate from the watch/confirm path."""
        with get_connection() as conn:
            row = conn.execute(
                "UPDATE cached_episodes SET status = %s, updated_at = %s "
                "WHERE id = %s AND status = %s RETURNING id",
                (STATUS_DOWNLOADING, _now_iso(), entry_id, STATUS_PENDING),
            ).fetchone()
        return row is not None

    def mark_ready(self, entry_id: int, file_size: int) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE cached_episodes SET status = %s, file_size = %s, error = NULL, updated_at = %s WHERE id = %s",
                (STATUS_READY, file_size, _now_iso(), entry_id),
            )

    def mark_failed(self, entry_id: int, error: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE cached_episodes SET status = %s, error = %s, updated_at = %s WHERE id = %s",
                (STATUS_FAILED, (error or "")[:500], _now_iso(), entry_id),
            )

    def delete_episode(self, entry_id: int) -> Optional[dict]:
        """Delete a cache row, returning it (so the caller can unlink the file)."""
        with get_connection() as conn:
            return conn.execute(
                f"DELETE FROM cached_episodes WHERE id = %s RETURNING {_EP_COLS}", (entry_id,)
            ).fetchone()

    def reset_stale_jobs(self) -> int:
        """On worker startup, requeue any orphaned in-progress download by flipping
        it ``downloading`` -> ``pending`` so this worker simply picks it up again. A
        row stuck in ``downloading`` belongs to a previous worker that died mid-remux
        (a deploy that outran ``stop_grace_period``, a crash); the old "interrupted by
        restart" failure is gone — it auto-retries instead. Returns the number
        requeued.

        ``pending`` rows are deliberately left untouched: they're durable claims the
        api's ``/cache/confirm`` wrote that no worker has started yet — the poll loop
        will drain them. Safe to reset ``downloading`` here because the cache-worker
        deploys stop-first (never two at once), so at startup any ``downloading`` row
        is genuinely orphaned, not actively held by a peer."""
        with get_connection() as conn:
            rows = conn.execute(
                """
                UPDATE cached_episodes
                SET status = %s, error = NULL, updated_at = %s
                WHERE status = %s
                RETURNING id
                """,
                (STATUS_PENDING, _now_iso(), STATUS_DOWNLOADING),
            ).fetchall()
        return len(rows)

    # ----------------------------------------------------------------- cache
    @staticmethod
    def _bump() -> None:
        CacheStore._targets_cache = None
        CacheStore._targets_cache_at = 0.0
