"""Postgres store for the server-side video cache.

| table             | holds                                                   |
|-------------------|---------------------------------------------------------|
| cache_targets     | NAS directories open for caching, with a display name   |
| cache_settings    | the single-row master switch                            |
| cached_episodes   | one row per cached file and its download lifecycle      |

The ``cached_episodes`` row is also the job queue: an api replica writes a
``pending`` row and the cache-worker service claims and downloads it.
"""

from __future__ import annotations

import time
from typing import List, Optional

from core.db_pool import get_connection, lock_schema_init
from core.clock import utc_now_iso

_TARGET_COLS = "id, name, path, enabled, created_at"
_EP_COLS = (
    "id, target_id, tmdb_id, media_type, season_number, episode_number, anilist_id, "
    "language, source_origin, rel_path, container, file_size, status, error, "
    "created_at, updated_at"
)
_EP_COLS_CE = ", ".join("ce." + c for c in _EP_COLS.split(", "))

STATUS_PENDING = "pending"
STATUS_DOWNLOADING = "downloading"
STATUS_READY = "ready"
STATUS_FAILED = "failed"

# The switch and the target list are read on every /watch stream, scrape and
# /cache_proxy request, so both are held for a few seconds. Writes on this
# replica invalidate at once; other replicas converge within the TTL.
_READ_TTL = 5.0


class CacheStore:
    _targets_cache: Optional[List[dict]] = None
    _targets_cache_at: float = 0.0
    _enabled_cache: Optional[bool] = None
    _enabled_cache_at: float = 0.0

    def init_db(self) -> None:
        with get_connection() as conn:
            lock_schema_init(conn)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cache_targets (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name       TEXT NOT NULL,
                    path       TEXT NOT NULL UNIQUE,
                    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TEXT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cache_settings (
                    id         INTEGER PRIMARY KEY DEFAULT 1,
                    enabled    BOOLEAN NOT NULL DEFAULT FALSE,
                    updated_at TEXT NOT NULL,
                    CONSTRAINT cache_settings_singleton CHECK (id = 1)
                );
                """
            )
            conn.execute(
                """
                INSERT INTO cache_settings (id, enabled, updated_at)
                VALUES (1, FALSE, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                (utc_now_iso(),),
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS cached_episodes (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    target_id      BIGINT NOT NULL REFERENCES cache_targets(id) ON DELETE CASCADE,
                    tmdb_id        BIGINT NOT NULL,
                    media_type     TEXT NOT NULL DEFAULT 'tv',
                    season_number  INTEGER NOT NULL,
                    episode_number INTEGER NOT NULL,
                    anilist_id     BIGINT,
                    language       TEXT NOT NULL DEFAULT '',
                    source_origin  TEXT NOT NULL DEFAULT '',
                    rel_path       TEXT NOT NULL,
                    media_url      TEXT,
                    container      TEXT NOT NULL DEFAULT 'mp4',
                    file_size      BIGINT,
                    status         TEXT NOT NULL DEFAULT 'pending',
                    error          TEXT,
                    created_at     TEXT NOT NULL,
                    updated_at     TEXT NOT NULL
                );
                """
            )
            # claim_download's ON CONFLICT infers this index by its column list.
            conn.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS cached_episodes_uniq "
                "ON cached_episodes (media_type, tmdb_id, season_number, episode_number, language)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS cached_episodes_lookup "
                "ON cached_episodes (media_type, tmdb_id, season_number, episode_number, status)"
            )

    def get_enabled(self) -> bool:
        now = time.monotonic()
        cached = CacheStore._enabled_cache
        if cached is not None and (now - CacheStore._enabled_cache_at) < _READ_TTL:
            return cached
        try:
            with get_connection() as conn:
                row = conn.execute("SELECT enabled FROM cache_settings WHERE id = 1").fetchone()
        except Exception:
            return False
        enabled = bool(row["enabled"]) if row else False
        CacheStore._enabled_cache = enabled
        CacheStore._enabled_cache_at = now
        return enabled

    def set_enabled(self, enabled: bool) -> bool:
        with get_connection() as conn:
            conn.execute(
                """
                INSERT INTO cache_settings (id, enabled, updated_at)
                VALUES (1, %s, %s)
                ON CONFLICT (id) DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = EXCLUDED.updated_at
                """,
                (enabled, utc_now_iso()),
            )
        self._bump()
        return enabled

    def list_targets(self) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_TARGET_COLS} FROM cache_targets ORDER BY created_at, id"
            ).fetchall()

    def get_target(self, target_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_TARGET_COLS} FROM cache_targets WHERE id = %s", (target_id,)
            ).fetchone()

    def enabled_targets(self) -> List[dict]:
        now = time.monotonic()
        cached = CacheStore._targets_cache
        if cached is not None and (now - CacheStore._targets_cache_at) < _READ_TTL:
            return cached
        try:
            with get_connection() as conn:
                rows = conn.execute(
                    f"SELECT {_TARGET_COLS} FROM cache_targets WHERE enabled = TRUE ORDER BY created_at, id"
                ).fetchall()
        except Exception:
            return cached or []
        CacheStore._targets_cache = rows
        CacheStore._targets_cache_at = now
        return rows

    def add_target(self, name: str, path: str) -> dict:
        with get_connection() as conn:
            row = conn.execute(
                f"""
                INSERT INTO cache_targets (name, path, enabled, created_at)
                VALUES (%s, %s, TRUE, %s)
                RETURNING {_TARGET_COLS}
                """,
                (name, path, utc_now_iso()),
            ).fetchone()
        self._bump()
        return row

    def update_target(
        self, target_id: int, name: Optional[str] = None, enabled: Optional[bool] = None
    ) -> Optional[dict]:
        sets: list[str] = []
        vals: list = []
        if name is not None:
            sets.append("name = %s")
            vals.append(name)
        if enabled is not None:
            sets.append("enabled = %s")
            vals.append(enabled)
        if not sets:
            return self.get_target(target_id)
        vals.append(target_id)
        with get_connection() as conn:
            row = conn.execute(
                f"UPDATE cache_targets SET {', '.join(sets)} WHERE id = %s RETURNING {_TARGET_COLS}",
                tuple(vals),
            ).fetchone()
        self._bump()
        return row

    def delete_target(self, target_id: int) -> bool:
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM cache_targets WHERE id = %s RETURNING id", (target_id,)
            ).fetchone()
        self._bump()
        return row is not None

    def ready_for_episode(
        self, tmdb_id: int, season_number: int, episode_number: int, media_type: str = "tv"
    ) -> List[dict]:
        """Ready files for an episode (a movie is season 0, episode 0) with their
        target's name. Joining on enabled targets is what hides a disabled target's
        files immediately."""
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {_EP_COLS_CE},
                       ct.name AS target_name, ct.path AS target_path
                FROM cached_episodes ce
                JOIN cache_targets ct ON ct.id = ce.target_id AND ct.enabled = TRUE
                WHERE ce.media_type = %s AND ce.tmdb_id = %s AND ce.season_number = %s
                      AND ce.episode_number = %s AND ce.status = %s
                ORDER BY ce.language
                """,
                (media_type, tmdb_id, season_number, episode_number, STATUS_READY),
            ).fetchall()

    def list_episodes(
        self, status: Optional[str] = None, limit: int = 100, offset: int = 0
    ) -> List[dict]:
        where = ""
        params: list = []
        if status:
            where = "WHERE ce.status = %s"
            params.append(status)
        params.extend([limit, offset])
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {_EP_COLS_CE},
                       ct.name AS target_name
                FROM cached_episodes ce
                LEFT JOIN cache_targets ct ON ct.id = ce.target_id
                {where}
                ORDER BY ce.updated_at DESC, ce.id DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()

    def count_episodes(self, status: Optional[str] = None) -> int:
        with get_connection() as conn:
            if status:
                row = conn.execute(
                    "SELECT COUNT(*) AS n FROM cached_episodes WHERE status = %s", (status,)
                ).fetchone()
            else:
                row = conn.execute("SELECT COUNT(*) AS n FROM cached_episodes").fetchone()
        return row["n"] if row else 0

    def stats(self) -> dict:
        out = {"ready": 0, "pending": 0, "downloading": 0, "failed": 0, "total_bytes": 0}
        try:
            with get_connection() as conn:
                for r in conn.execute(
                    "SELECT status, COUNT(*) AS n FROM cached_episodes GROUP BY status"
                ).fetchall():
                    out[r["status"]] = r["n"]
                row = conn.execute(
                    "SELECT COALESCE(SUM(file_size), 0) AS b FROM cached_episodes WHERE status = 'ready'"
                ).fetchone()
                out["total_bytes"] = int(row["b"]) if row else 0
        except Exception:
            pass
        return out

    def claim_download(
        self,
        *,
        tmdb_id: int,
        media_type: str,
        season_number: int,
        episode_number: int,
        anilist_id: Optional[int],
        language: str,
        source_origin: str,
        target_id: int,
        rel_path: str,
        media_url: str,
        container: str = "mp4",
    ) -> Optional[dict]:
        """Insert a ``pending`` row, or revive a ``failed`` one. Returns None when a
        live row already exists: the unique index is the cross-replica dedup point.
        ``media_url`` is stored so the separate cache-worker can run the download."""
        now = utc_now_iso()
        with get_connection() as conn:
            return conn.execute(
                f"""
                INSERT INTO cached_episodes
                    (target_id, tmdb_id, media_type, season_number, episode_number, anilist_id,
                     language, source_origin, rel_path, media_url, container, status, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (media_type, tmdb_id, season_number, episode_number, language)
                DO UPDATE SET
                    status = EXCLUDED.status,
                    target_id = EXCLUDED.target_id,
                    rel_path = EXCLUDED.rel_path,
                    media_url = EXCLUDED.media_url,
                    source_origin = EXCLUDED.source_origin,
                    anilist_id = EXCLUDED.anilist_id,
                    container = EXCLUDED.container,
                    error = NULL,
                    file_size = NULL,
                    updated_at = EXCLUDED.updated_at
                WHERE cached_episodes.status = %s
                RETURNING {_EP_COLS}
                """,
                (
                    target_id, tmdb_id, media_type, season_number, episode_number, anilist_id,
                    language, source_origin, rel_path, media_url, container, STATUS_PENDING, now, now,
                    STATUS_FAILED,
                ),
            ).fetchone()

    def fetch_pending(self, limit: int = 8) -> List[dict]:
        """Oldest ``pending`` rows whose target is still enabled, with its path."""
        with get_connection() as conn:
            return conn.execute(
                """
                SELECT ce.id, ce.tmdb_id, ce.media_type, ce.season_number, ce.episode_number,
                       ce.language, ce.source_origin, ce.rel_path, ce.media_url,
                       ct.path AS target_path
                FROM cached_episodes ce
                JOIN cache_targets ct ON ct.id = ce.target_id AND ct.enabled = TRUE
                WHERE ce.status = %s
                ORDER BY ce.created_at, ce.id
                LIMIT %s
                """,
                (STATUS_PENDING, limit),
            ).fetchall()

    def begin_download(self, entry_id: int) -> bool:
        """``pending`` to ``downloading``; False when someone else claimed it first."""
        with get_connection() as conn:
            row = conn.execute(
                "UPDATE cached_episodes SET status = %s, updated_at = %s "
                "WHERE id = %s AND status = %s RETURNING id",
                (STATUS_DOWNLOADING, utc_now_iso(), entry_id, STATUS_PENDING),
            ).fetchone()
        return row is not None

    def mark_ready(self, entry_id: int, file_size: int) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE cached_episodes SET status = %s, file_size = %s, error = NULL, updated_at = %s WHERE id = %s",
                (STATUS_READY, file_size, utc_now_iso(), entry_id),
            )

    def mark_failed(self, entry_id: int, error: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE cached_episodes SET status = %s, error = %s, updated_at = %s WHERE id = %s",
                (STATUS_FAILED, (error or "")[:500], utc_now_iso(), entry_id),
            )

    def delete_episode(self, entry_id: int) -> Optional[dict]:
        """Returns the deleted row so the caller can unlink the file."""
        with get_connection() as conn:
            return conn.execute(
                f"DELETE FROM cached_episodes WHERE id = %s RETURNING {_EP_COLS}", (entry_id,)
            ).fetchone()

    def reset_stale_jobs(self) -> int:
        """On worker startup, put every ``downloading`` row back to ``pending``.
        Safe only because the cache-worker deploys stop-first: at startup no peer
        can be holding one, so each belongs to a worker that died mid-remux."""
        with get_connection() as conn:
            rows = conn.execute(
                """
                UPDATE cached_episodes
                SET status = %s, error = NULL, updated_at = %s
                WHERE status = %s
                RETURNING id
                """,
                (STATUS_PENDING, utc_now_iso(), STATUS_DOWNLOADING),
            ).fetchall()
        return len(rows)

    @staticmethod
    def _bump() -> None:
        CacheStore._targets_cache = None
        CacheStore._enabled_cache = None


store = CacheStore()
