"""
PostgreSQL store for the admin download queue.

The Admin Dashboard hands the backend a URL (plain http/https) or a ``magnet:``
link; the file is fetched in the background by an **aria2c** sidecar and landed
under ``<root>/crimson-downloads/`` on the first *download-enabled* local source
with enough free space (see ``download_engine.fs`` / ``download_engine.manager``).
Once on disk the existing ``local_engine`` library scanner surfaces it like any
other on-disk title — no separate playback path.

One table, ``download_jobs`` — one row per submitted download, carrying the whole
lifecycle:

    pending  -> the row a route wrote; awaiting the download-worker.
    active   -> handed to aria2 (``gid`` set); bytes/speed updated as it runs.
    paused   -> admin-paused (aria2 paused if it had started).
    complete -> finished and moved out of staging into crimson-downloads.
    failed   -> aria2 error / move error (``error`` carries the reason).

Mirrors cache_engine.db / local_engine.db: plain pooled psycopg calls borrowing
from the shared pool (db_pool), driven from api.py's async handlers via
``run_in_threadpool``. Volumes are tiny (a handful of rows).

The DB row is the queue (like the video cache): a route on any replica writes a
``pending`` row, and only the dedicated download-worker (RUN_DOWNLOAD_WORKER)
submits it to aria2 and polls it — so a download survives an api redeploy, and
``begin_submit`` is the cross-worker claim that stops two workers double-adding
the same job.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from core.db_pool import get_connection, lock_schema_init

_COLS = (
    "id, kind, source_url, name, target_source_id, target_path, dest_dir, "
    "staging_dir, gid, status, bytes_total, bytes_done, download_speed, "
    "final_path, error, created_by, created_at, updated_at"
)

# Lifecycle states for a download_jobs row.
STATUS_PENDING = "pending"
STATUS_ACTIVE = "active"
STATUS_PAUSED = "paused"
STATUS_COMPLETE = "complete"
STATUS_FAILED = "failed"

# Download kinds.
KIND_HTTP = "http"
KIND_TORRENT = "torrent"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class DownloadStore:
    """Data layer for the ``download_jobs`` table."""

    # ----------------------------------------------------------------- schema
    def init_db(self) -> None:
        """Create the schema (idempotent)."""
        with get_connection() as conn:
            lock_schema_init(conn)  # serialize DDL across replicas (see db_pool)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS download_jobs (
                    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    kind             TEXT NOT NULL,
                    source_url       TEXT NOT NULL,
                    name             TEXT,
                    target_source_id BIGINT,
                    target_path      TEXT,
                    dest_dir         TEXT,
                    staging_dir      TEXT,
                    gid              TEXT,
                    status           TEXT NOT NULL DEFAULT 'pending',
                    bytes_total      BIGINT,
                    bytes_done       BIGINT NOT NULL DEFAULT 0,
                    download_speed   BIGINT NOT NULL DEFAULT 0,
                    final_path       TEXT,
                    error            TEXT,
                    created_by       TEXT,
                    created_at       TEXT NOT NULL,
                    updated_at       TEXT NOT NULL
                );
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS download_jobs_status "
                "ON download_jobs (status, created_at, id)"
            )

    # ------------------------------------------------------------------ reads
    def list_jobs(
        self, status: Optional[str] = None, limit: int = 100, offset: int = 0
    ) -> List[dict]:
        where, params = "", []
        if status:
            where = "WHERE status = %s"
            params.append(status)
        params.extend([limit, offset])
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {_COLS} FROM download_jobs
                {where}
                ORDER BY
                    CASE status WHEN 'active' THEN 0 WHEN 'pending' THEN 1
                                WHEN 'paused' THEN 2 ELSE 3 END,
                    updated_at DESC, id DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()

    def count_jobs(self, status: Optional[str] = None) -> int:
        with get_connection() as conn:
            if status:
                row = conn.execute(
                    "SELECT COUNT(*) AS n FROM download_jobs WHERE status = %s", (status,)
                ).fetchone()
            else:
                row = conn.execute("SELECT COUNT(*) AS n FROM download_jobs").fetchone()
        return row["n"] if row else 0

    def get_job(self, job_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE id = %s", (job_id,)
            ).fetchone()

    def fetch_pending(self, limit: int = 8) -> List[dict]:
        """Oldest ``pending`` rows for the worker to submit to aria2."""
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE status = %s "
                "ORDER BY created_at, id LIMIT %s",
                (STATUS_PENDING, limit),
            ).fetchall()

    def fetch_active(self) -> List[dict]:
        """All ``active`` rows (already handed to aria2) for the worker to poll."""
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE status = %s ORDER BY id",
                (STATUS_ACTIVE,),
            ).fetchall()

    def count_active(self) -> int:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM download_jobs WHERE status = %s", (STATUS_ACTIVE,)
            ).fetchone()
        return row["n"] if row else 0

    def stats(self) -> dict:
        """Aggregate counts + total downloaded bytes, for the dashboard."""
        out = {"pending": 0, "active": 0, "paused": 0, "complete": 0, "failed": 0, "total_bytes": 0}
        try:
            with get_connection() as conn:
                for r in conn.execute(
                    "SELECT status, COUNT(*) AS n FROM download_jobs GROUP BY status"
                ).fetchall():
                    out[r["status"]] = r["n"]
                row = conn.execute(
                    "SELECT COALESCE(SUM(bytes_done), 0) AS b FROM download_jobs WHERE status = 'complete'"
                ).fetchone()
                out["total_bytes"] = int(row["b"]) if row else 0
        except Exception:
            pass
        return out

    # ----------------------------------------------------------------- writes
    def create_job(
        self, kind: str, source_url: str, name: Optional[str], created_by: str
    ) -> dict:
        """Write a fresh ``pending`` job (the target root + staging dir are chosen
        later, by the worker, so free space is checked when the download actually
        starts)."""
        now = _now_iso()
        with get_connection() as conn:
            return conn.execute(
                f"""
                INSERT INTO download_jobs (kind, source_url, name, status, created_by, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING {_COLS}
                """,
                (kind, source_url, name, STATUS_PENDING, created_by, now, now),
            ).fetchone()

    def begin_submit(self, job_id: int) -> bool:
        """Atomically claim a ``pending`` row so exactly one worker submits it. Leaves
        it ``pending`` (still) but stamps ``updated_at`` — the caller flips it to
        ``active`` via :meth:`mark_active` once aria2 has accepted it. Returns True if
        THIS caller won the row. Cross-worker/replica claim point (mirrors the video
        cache's ``begin_download``)."""
        with get_connection() as conn:
            row = conn.execute(
                "UPDATE download_jobs SET updated_at = %s "
                "WHERE id = %s AND status = %s RETURNING id",
                (_now_iso(), job_id, STATUS_PENDING),
            ).fetchone()
        return row is not None

    def mark_active(
        self,
        job_id: int,
        *,
        gid: str,
        target_source_id: int,
        target_path: str,
        dest_dir: str,
        staging_dir: str,
    ) -> Optional[dict]:
        """Record the aria2 gid + the chosen destination and flip the row to
        ``active``."""
        with get_connection() as conn:
            return conn.execute(
                f"""
                UPDATE download_jobs
                SET status = %s, gid = %s, target_source_id = %s, target_path = %s,
                    dest_dir = %s, staging_dir = %s, error = NULL, updated_at = %s
                WHERE id = %s
                RETURNING {_COLS}
                """,
                (STATUS_ACTIVE, gid, target_source_id, target_path, dest_dir,
                 staging_dir, _now_iso(), job_id),
            ).fetchone()

    def update_gid(self, job_id: int, gid: str) -> None:
        """Follow aria2's metadata->data gid switch (a magnet's real download gets a
        new gid once metadata resolves; see download_engine.manager)."""
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET gid = %s, updated_at = %s WHERE id = %s",
                (gid, _now_iso(), job_id),
            )

    def update_progress(
        self, job_id: int, bytes_done: int, bytes_total: Optional[int], speed: int
    ) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET bytes_done = %s, bytes_total = %s, "
                "download_speed = %s, updated_at = %s WHERE id = %s",
                (bytes_done, bytes_total, speed, _now_iso(), job_id),
            )

    def mark_complete(self, job_id: int, final_path: str, bytes_done: int) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET status = %s, final_path = %s, bytes_done = %s, "
                "download_speed = 0, error = NULL, updated_at = %s WHERE id = %s",
                (STATUS_COMPLETE, final_path, bytes_done, _now_iso(), job_id),
            )

    def mark_failed(self, job_id: int, error: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET status = %s, download_speed = 0, error = %s, "
                "updated_at = %s WHERE id = %s",
                (STATUS_FAILED, (error or "")[:500], _now_iso(), job_id),
            )

    def set_status(self, job_id: int, status: str) -> Optional[dict]:
        """Directly set a row's status (used by pause/resume/retry)."""
        with get_connection() as conn:
            return conn.execute(
                f"UPDATE download_jobs SET status = %s, updated_at = %s WHERE id = %s "
                f"RETURNING {_COLS}",
                (status, _now_iso(), job_id),
            ).fetchone()

    def requeue(self, job_id: int) -> Optional[dict]:
        """Reset a row to ``pending`` and clear its aria2 gid so the worker submits it
        afresh (used to retry a failed job and, on worker startup, to reclaim rows the
        old worker was mid-download on — aria2 resumes from the control file left in the
        staging dir)."""
        with get_connection() as conn:
            return conn.execute(
                f"UPDATE download_jobs SET status = %s, gid = NULL, download_speed = 0, "
                f"error = NULL, updated_at = %s WHERE id = %s RETURNING {_COLS}",
                (STATUS_PENDING, _now_iso(), job_id),
            ).fetchone()

    def delete_job(self, job_id: int) -> Optional[dict]:
        """Delete a row, returning it (so the caller can remove it from aria2 + clean
        the staging dir)."""
        with get_connection() as conn:
            return conn.execute(
                f"DELETE FROM download_jobs WHERE id = %s RETURNING {_COLS}", (job_id,)
            ).fetchone()
