"""Postgres store for the admin download queue: one ``download_jobs`` row per
submitted URL or magnet, which is also the job queue the download-worker drains.

| status   | meaning                                                   |
|----------|-----------------------------------------------------------|
| pending  | written by a route, waiting for the worker                |
| active   | handed to aria2 (``gid`` set), progress updated per poll  |
| paused   | paused by the admin                                       |
| complete | moved out of staging into ``crimson-downloads``           |
| failed   | aria2 or move error, reason in ``error``                  |

Finished files are surfaced by the Local library scanner like any other title.
"""

from __future__ import annotations

from typing import List, Optional

from core.db_pool import get_connection, lock_schema_init
from core.clock import utc_now_iso

_COLS = (
    "id, kind, source_url, name, target_source_id, target_path, dest_dir, "
    "staging_dir, gid, status, bytes_total, bytes_done, download_speed, "
    "final_path, error, created_by, created_at, updated_at"
)

STATUS_PENDING = "pending"
STATUS_ACTIVE = "active"
STATUS_PAUSED = "paused"
STATUS_COMPLETE = "complete"
STATUS_FAILED = "failed"

KIND_HTTP = "http"
KIND_TORRENT = "torrent"


class DownloadStore:
    def init_db(self) -> None:
        with get_connection() as conn:
            lock_schema_init(conn)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS download_jobs (
                    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    kind             TEXT NOT NULL,
                    source_url       TEXT NOT NULL,
                    name             TEXT,
                    target_source_id BIGINT,
                    target_path      TEXT,
                    dest_dir         TEXT,
                    staging_dir      TEXT,
                    gid              TEXT,
                    status           TEXT NOT NULL DEFAULT 'pending',
                    bytes_total      BIGINT,
                    bytes_done       BIGINT NOT NULL DEFAULT 0,
                    download_speed   BIGINT NOT NULL DEFAULT 0,
                    final_path       TEXT,
                    error            TEXT,
                    created_by       TEXT,
                    created_at       TEXT NOT NULL,
                    updated_at       TEXT NOT NULL
                );
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS download_jobs_status "
                "ON download_jobs (status, created_at, id)"
            )

    def list_jobs(
        self, status: Optional[str] = None, limit: int = 100, offset: int = 0
    ) -> List[dict]:
        where = ""
        params: list = []
        if status:
            where = "WHERE status = %s"
            params.append(status)
        params.extend([limit, offset])
        with get_connection() as conn:
            return conn.execute(
                f"""
                SELECT {_COLS} FROM download_jobs
                {where}
                ORDER BY
                    CASE status WHEN 'active' THEN 0 WHEN 'pending' THEN 1
                                WHEN 'paused' THEN 2 ELSE 3 END,
                    updated_at DESC, id DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()

    def count_jobs(self, status: Optional[str] = None) -> int:
        with get_connection() as conn:
            if status:
                row = conn.execute(
                    "SELECT COUNT(*) AS n FROM download_jobs WHERE status = %s", (status,)
                ).fetchone()
            else:
                row = conn.execute("SELECT COUNT(*) AS n FROM download_jobs").fetchone()
        return row["n"] if row else 0

    def get_job(self, job_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE id = %s", (job_id,)
            ).fetchone()

    def fetch_pending(self, limit: int = 8) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE status = %s "
                "ORDER BY created_at, id LIMIT %s",
                (STATUS_PENDING, limit),
            ).fetchall()

    def fetch_active(self) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM download_jobs WHERE status = %s ORDER BY id",
                (STATUS_ACTIVE,),
            ).fetchall()

    def count_active(self) -> int:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM download_jobs WHERE status = %s", (STATUS_ACTIVE,)
            ).fetchone()
        return row["n"] if row else 0

    def stats(self) -> dict:
        out = {"pending": 0, "active": 0, "paused": 0, "complete": 0, "failed": 0, "total_bytes": 0}
        try:
            with get_connection() as conn:
                for r in conn.execute(
                    "SELECT status, COUNT(*) AS n FROM download_jobs GROUP BY status"
                ).fetchall():
                    out[r["status"]] = r["n"]
                row = conn.execute(
                    "SELECT COALESCE(SUM(bytes_done), 0) AS b FROM download_jobs WHERE status = 'complete'"
                ).fetchone()
                out["total_bytes"] = int(row["b"]) if row else 0
        except Exception:
            pass
        return out

    def create_job(
        self, kind: str, source_url: str, name: Optional[str], created_by: str
    ) -> dict:
        """The target root is chosen later by the worker, so free space is checked
        when the download actually starts."""
        now = utc_now_iso()
        with get_connection() as conn:
            return conn.execute(
                f"""
                INSERT INTO download_jobs (kind, source_url, name, status, created_by, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING {_COLS}
                """,
                (kind, source_url, name, STATUS_PENDING, created_by, now, now),
            ).fetchone()

    def mark_active(
        self,
        job_id: int,
        *,
        gid: str,
        target_source_id: int,
        target_path: str,
        dest_dir: str,
        staging_dir: str,
    ) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"""
                UPDATE download_jobs
                SET status = %s, gid = %s, target_source_id = %s, target_path = %s,
                    dest_dir = %s, staging_dir = %s, error = NULL, updated_at = %s
                WHERE id = %s
                RETURNING {_COLS}
                """,
                (STATUS_ACTIVE, gid, target_source_id, target_path, dest_dir,
                 staging_dir, utc_now_iso(), job_id),
            ).fetchone()

    def update_gid(self, job_id: int, gid: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET gid = %s, updated_at = %s WHERE id = %s",
                (gid, utc_now_iso(), job_id),
            )

    def update_progress(
        self, job_id: int, bytes_done: int, bytes_total: Optional[int], speed: int
    ) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET bytes_done = %s, bytes_total = %s, "
                "download_speed = %s, updated_at = %s WHERE id = %s",
                (bytes_done, bytes_total, speed, utc_now_iso(), job_id),
            )

    def mark_complete(self, job_id: int, final_path: str, bytes_done: int) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET status = %s, final_path = %s, bytes_done = %s, "
                "download_speed = 0, error = NULL, updated_at = %s WHERE id = %s",
                (STATUS_COMPLETE, final_path, bytes_done, utc_now_iso(), job_id),
            )

    def mark_failed(self, job_id: int, error: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE download_jobs SET status = %s, download_speed = 0, error = %s, "
                "updated_at = %s WHERE id = %s",
                (STATUS_FAILED, (error or "")[:500], utc_now_iso(), job_id),
            )

    def set_status(self, job_id: int, status: str) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"UPDATE download_jobs SET status = %s, updated_at = %s WHERE id = %s "
                f"RETURNING {_COLS}",
                (status, utc_now_iso(), job_id),
            ).fetchone()

    def requeue(self, job_id: int) -> Optional[dict]:
        """Back to ``pending`` without a gid, so the worker resubmits it. aria2
        resumes from the control file left in the staging dir."""
        with get_connection() as conn:
            return conn.execute(
                f"UPDATE download_jobs SET status = %s, gid = NULL, download_speed = 0, "
                f"error = NULL, updated_at = %s WHERE id = %s RETURNING {_COLS}",
                (STATUS_PENDING, utc_now_iso(), job_id),
            ).fetchone()

    def delete_job(self, job_id: int) -> Optional[dict]:
        """Returns the deleted row so the caller can clean up aria2 and staging."""
        with get_connection() as conn:
            return conn.execute(
                f"DELETE FROM download_jobs WHERE id = %s RETURNING {_COLS}", (job_id,)
            ).fetchone()


store = DownloadStore()
