-- 008_music.sql
--
-- The music library: playlists imported from Spotify (or a CSV export), the
-- tracks they hold, and the per-account Spotify link that keeps them in sync.
--
-- | table                 | holds                                                  |
-- | --------------------- | ------------------------------------------------------ |
-- | music_spotify_links   | one account's Spotify app client ID and refresh token  |
-- | music_playlists       | an imported playlist, owned by one account             |
-- | music_tracks          | one row per recording, shared by every playlist        |
-- | music_playlist_tracks | which tracks a playlist holds, in order                |
--
-- Access is deny by default, like Lumi: music_enabled on the account is
-- granted per user from the admin Users tab (PATCH /admin/users/{id}).
--
-- A track is keyed by its Spotify id where one is known (every Spotify import,
-- most CSV exports), else by ISRC or a hash of artist, title and length. Two
-- playlists (or two accounts) holding the same song share one row and one file. Nothing here deletes a file:
-- a song Spotify drops from a playlist keeps its row, its link to the playlist
-- (removed_upstream) and its audio, which is the reason the feature exists.
--
-- music_tracks is also the download queue. An import writes 'pending' rows and
-- the music-worker service claims them:
--
--   pending -> working -> ready
--                      -> review     candidates saved, a person picks one
--                      -> unmatched  nothing looked like this recording
--                      -> failed     the download or tagging broke

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS music_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS music_spotify_links (
    user_id           BIGINT PRIMARY KEY REFERENCES accounts(user_id) ON DELETE CASCADE,
    -- The account's own Spotify app. There is no client secret: the flow is
    -- Authorization Code with PKCE, so this ID is all a refresh needs.
    client_id         TEXT NOT NULL,
    -- Spotify rotates it on every refresh, so it is rewritten together with the
    -- access token in one statement.
    refresh_token     TEXT NOT NULL,
    access_token      TEXT,
    access_expires_at TEXT,
    spotify_user_id   TEXT,
    display_name      TEXT,
    scope             TEXT,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS music_playlists (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
    -- 'spotify' (Web API, or 'liked' for Liked Songs), 'public' (the embed
    -- fallback) or 'csv' (a one-off import that never syncs).
    source         TEXT NOT NULL,
    spotify_id     TEXT,
    name           TEXT NOT NULL,
    description    TEXT NOT NULL DEFAULT '',
    cover_url      TEXT,
    snapshot_id    TEXT,
    sync_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TEXT,
    last_error     TEXT,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);
-- NULL spotify_ids (CSV imports) never collide, so a CSV can be imported twice.
CREATE UNIQUE INDEX IF NOT EXISTS music_playlists_uniq
    ON music_playlists (user_id, source, spotify_id);

CREATE TABLE IF NOT EXISTS music_tracks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_key     TEXT NOT NULL UNIQUE,
    spotify_id    TEXT,
    isrc          TEXT,
    title         TEXT NOT NULL,
    artists       JSONB NOT NULL DEFAULT '[]',
    album         TEXT NOT NULL DEFAULT '',
    album_artist  TEXT NOT NULL DEFAULT '',
    track_number  INTEGER,
    disc_number   INTEGER,
    release_date  TEXT,
    duration_ms   INTEGER NOT NULL DEFAULT 0,
    cover_url     TEXT,
    status        TEXT NOT NULL DEFAULT 'pending',
    -- The recording to download. Set by the matcher, or by a person, in which
    -- case match_manual keeps the matcher from ever second-guessing it.
    match_url     TEXT,
    match_manual  BOOLEAN NOT NULL DEFAULT FALSE,
    candidates    JSONB,
    rel_path      TEXT,
    cover_path    TEXT,
    file_size     BIGINT,
    attempts      INTEGER NOT NULL DEFAULT 0,
    error         TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS music_tracks_status ON music_tracks (status, created_at);

CREATE TABLE IF NOT EXISTS music_playlist_tracks (
    playlist_id      BIGINT NOT NULL REFERENCES music_playlists(id) ON DELETE CASCADE,
    track_id         BIGINT NOT NULL REFERENCES music_tracks(id) ON DELETE CASCADE,
    position         INTEGER NOT NULL,
    added_at         TEXT,
    removed_upstream BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (playlist_id, track_id)
);
CREATE INDEX IF NOT EXISTS music_playlist_tracks_track ON music_playlist_tracks (track_id);
