"""Security event log: who tried to get in, what was denied, what an admin changed.

An append-only table fed from the auth flows, admin actions and the 429
handler. Not fed by the site-wide login wall, which every internet bot hits and
would drown the signal. Writes never raise, so a failing log can degrade the
ledger but never a login.

Raw client IPs and the attempted identity are stored, never a full public key,
password or token. Rows past SECURITY_EVENTS_RETENTION_DAYS are pruned.
"""

from __future__ import annotations

import json
import logging
from datetime import timedelta
from typing import Dict, List, Optional

from core import errors
from core.config import get_settings
from core.db_pool import get_connection, lock_schema_init
from core.clock import utc_now

logger = logging.getLogger(__name__)

# Caps so a hostile client cannot bloat rows with crafted inputs.
MAX_IDENTITY_LEN = 200
MAX_USER_AGENT_LEN = 300
MAX_DETAIL_LEN = 2000

# The dashboard's filter list. log_event accepts unknown types too.
EVENT_TYPES = (
    "login_success",            # a session was issued (email or mnemonic)
    "login_failed",             # bad credentials / bad signature / unknown key
    "login_unverified",         # correct password, but the email isn't verified yet
    "register_success",         # an account was created
    "register_blocked",         # signup denied: email taken / key already registered
    "invite_invalid",           # wrong or already-used invite code
    "email_verified",           # a verification link was consumed
    "verify_failed",            # invalid/expired verification token
    "verify_resend_requested",  # someone asked for a new verification link
    "password_reset_requested", # someone started a password reset
    "password_reset_success",   # a reset token was consumed, password changed
    "password_reset_failed",    # invalid/expired reset token
    "rate_limited",             # slowapi tripped a 429 on an auth-adjacent path
    "admin_action",             # an admin changed users / invites / bridge keys
    "session_revoked",          # the owner signed a session out
    "account_delete_failed",    # account deletion refused (bad confirmation)
    "account_deleted",          # the owner deleted their account
)

# 'failure' marks every denial, which is the attack signal; 'info' is for
# neutral events worth a paper trail that deny nothing.
OUTCOMES = ("success", "failure", "info")


def client_ip(request) -> Optional[str]:
    """The real client IP. uvicorn runs with ``--proxy-headers``, so this is
    already the X-Forwarded-For client, the same source core.rate_limit keys on."""
    try:
        return request.client.host if request and request.client else None
    except Exception:
        return None


def key_prefix(public_key: Optional[str]) -> Optional[str]:
    """A loggable handle for a mnemonic identity: enough to correlate repeat
    attempts, never the full key."""
    if not public_key:
        return None
    return f"{public_key[:12]}…"


def init_db() -> None:
    """``user_id`` has no foreign key so the trail survives the account being
    deleted. ``ts`` is TIMESTAMPTZ, unlike the account tables, because the
    charts need ``date_trunc``."""
    with get_connection() as conn:
        lock_schema_init(conn)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS security_events (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
                event_type TEXT NOT NULL,
                outcome    TEXT NOT NULL DEFAULT 'info',
                user_id    BIGINT,
                identity   TEXT,
                ip         TEXT,
                user_agent TEXT,
                detail     TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_secevents_ts ON security_events(ts);
            CREATE INDEX IF NOT EXISTS idx_secevents_type_ts ON security_events(event_type, ts);
            """
        )


def _clip(value: Optional[str], cap: int) -> Optional[str]:
    if value is None:
        return None
    s = str(value).strip()
    if not s:
        return None
    return s[:cap]


def encode_detail(detail: Optional[dict]) -> Optional[str]:
    """Serialize the context blob, dropping it (not the whole event) if it does
    not fit the cap or will not serialize."""
    if not detail:
        return None
    try:
        s = json.dumps(detail, ensure_ascii=False, default=str)
    except Exception:
        return None
    return s if len(s) <= MAX_DETAIL_LEN else None


def log_event(
    event_type: str,
    *,
    outcome: str = "info",
    request=None,
    user_id: Optional[int] = None,
    identity: Optional[str] = None,
    detail: Optional[dict] = None,
) -> None:
    """Record one security event. Never raises. Synchronous (one INSERT), so
    async callers run it in a thread."""
    try:
        if outcome not in OUTCOMES:
            outcome = "info"
        user_agent = request.headers.get("user-agent") if request is not None else None
        with get_connection() as conn:
            conn.execute(
                """
                INSERT INTO security_events (event_type, outcome, user_id, identity, ip, user_agent, detail)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    _clip(event_type, 60) or "unknown",
                    outcome,
                    user_id,
                    _clip(identity, MAX_IDENTITY_LEN),
                    _clip(client_ip(request), 64),
                    _clip(user_agent, MAX_USER_AGENT_LEN),
                    encode_detail(detail),
                ),
            )
    except Exception as e:
        logger.warning(f"security event log failed ({event_type}): {e}")


def _parse_detail(raw: Optional[str]):
    if not raw:
        return None
    try:
        return json.loads(raw)
    except Exception:
        return None


def _row_public(row: dict) -> dict:
    return {
        "id": row["id"],
        "ts": row["ts"].isoformat() if row.get("ts") else None,
        "event_type": row.get("event_type"),
        "outcome": row.get("outcome"),
        "user_id": row.get("user_id"),
        "identity": row.get("identity"),
        "ip": row.get("ip"),
        "user_agent": row.get("user_agent"),
        "detail": _parse_detail(row.get("detail")),
    }


def list_events(
    event_type: Optional[str] = None,
    outcome: Optional[str] = None,
    ip: Optional[str] = None,
    search: Optional[str] = None,
    hours: Optional[int] = None,
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """Newest-first page of the ledger. ``search`` matches identity/IP substrings."""
    where: List[str] = []
    params: List = []
    if event_type:
        where.append("event_type = %s")
        params.append(event_type)
    if outcome:
        where.append("outcome = %s")
        params.append(outcome)
    if ip:
        where.append("ip = %s")
        params.append(ip)
    if search:
        where.append("(identity ILIKE %s OR ip ILIKE %s)")
        like = f"%{search}%"
        params.extend([like, like])
    if hours:
        where.append("ts >= %s")
        params.append(utc_now() - timedelta(hours=hours))
    clause = f"WHERE {' AND '.join(where)}" if where else ""

    with get_connection() as conn:
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM security_events {clause}", params
        ).fetchone()["n"]
        rows = conn.execute(
            f"""
            SELECT * FROM security_events {clause}
            ORDER BY ts DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            params + [limit, offset],
        ).fetchall()
    return {"total": total, "events": [_row_public(r) for r in rows]}


def zero_filled_series(rows: List[dict], days: int, today) -> List[dict]:
    """Fold aggregate rows into one entry per calendar day, oldest first, with
    missing days at zero so the chart never has holes."""
    by_day: Dict[str, dict] = {}
    for offset in range(days - 1, -1, -1):
        day = (today - timedelta(days=offset)).isoformat()
        by_day[day] = {"day": day, "total": 0, "failures": 0, "by_type": {}}
    for r in rows:
        day = r["day"].isoformat() if hasattr(r["day"], "isoformat") else str(r["day"])
        slot = by_day.get(day)
        if slot is None:
            continue
        n = int(r["n"] or 0)
        slot["total"] += n
        if r["outcome"] == "failure":
            slot["failures"] += n
        slot["by_type"][r["event_type"]] = slot["by_type"].get(r["event_type"], 0) + n
    return list(by_day.values())


def fold_top_ips(rows: List[dict], limit: int = 10) -> List[dict]:
    """Fold failure aggregates into a ranked top-offenders list."""
    by_ip: Dict[str, dict] = {}
    for r in rows:
        ip = r.get("ip")
        if not ip:
            continue
        slot = by_ip.setdefault(ip, {"ip": ip, "count": 0, "last_seen": None, "types": {}})
        n = int(r["n"] or 0)
        slot["count"] += n
        slot["types"][r["event_type"]] = slot["types"].get(r["event_type"], 0) + n
        last = r.get("last_seen")
        last_iso = last.isoformat() if last is not None else None
        if last_iso and (slot["last_seen"] is None or last_iso > slot["last_seen"]):
            slot["last_seen"] = last_iso
    ranked = sorted(by_ip.values(), key=lambda s: s["count"], reverse=True)
    return ranked[:limit]


def fold_type_totals(rows: List[dict]) -> List[dict]:
    """Per (event_type, outcome) totals over the per-day rows, largest first."""
    totals: Dict[tuple, int] = {}
    for r in rows:
        key = (r["event_type"], r["outcome"])
        totals[key] = totals.get(key, 0) + int(r["n"] or 0)
    ranked = sorted(totals.items(), key=lambda kv: kv[1], reverse=True)
    return [{"event_type": t, "outcome": o, "count": n} for (t, o), n in ranked]


def stats(days: int = 14) -> dict:
    """Everything the Security tab needs in one payload."""
    days = max(1, min(days, 90))
    now = utc_now()
    since = now - timedelta(days=days - 1)
    day_start = since.replace(hour=0, minute=0, second=0, microsecond=0)
    last_24h = now - timedelta(hours=24)

    with get_connection() as conn:
        tiles = dict(conn.execute(
            """
            SELECT COUNT(*) FILTER (WHERE event_type IN ('login_failed', 'login_unverified'))
                       AS failed_logins_24h,
                   COUNT(*) FILTER (WHERE event_type = 'invite_invalid') AS invite_rejections_24h,
                   COUNT(*) FILTER (WHERE event_type = 'rate_limited')   AS rate_limited_24h,
                   COUNT(DISTINCT ip) FILTER (WHERE outcome = 'failure') AS offending_ips_24h
            FROM security_events WHERE ts >= %s
            """,
            (last_24h,),
        ).fetchone())
        tiles.update(conn.execute(
            """
            SELECT COUNT(*) FILTER (WHERE event_type = 'register_success') AS signups_window,
                   COUNT(*) AS events_window
            FROM security_events WHERE ts >= %s
            """,
            (day_start,),
        ).fetchone())

        series_rows = conn.execute(
            """
            SELECT date_trunc('day', ts)::date AS day, event_type, outcome, COUNT(*) AS n
            FROM security_events
            WHERE ts >= %s
            GROUP BY 1, 2, 3
            """,
            (day_start,),
        ).fetchall()

        ip_rows = conn.execute(
            """
            SELECT ip, event_type, COUNT(*) AS n, MAX(ts) AS last_seen
            FROM security_events
            WHERE ts >= %s AND outcome = 'failure' AND ip IS NOT NULL
            GROUP BY 1, 2
            """,
            (day_start,),
        ).fetchall()

        identity_rows = conn.execute(
            """
            SELECT identity, COUNT(*) AS n, MAX(ts) AS last_seen
            FROM security_events
            WHERE ts >= %s AND outcome = 'failure' AND identity IS NOT NULL
            GROUP BY 1
            ORDER BY COUNT(*) DESC
            LIMIT 8
            """,
            (day_start,),
        ).fetchall()

    return {
        "days": days,
        "retention_days": get_settings().security_events_retention_days,
        "tiles": tiles,
        "series": zero_filled_series(series_rows, days, now.date()),
        "by_type": fold_type_totals(series_rows),
        "top_ips": fold_top_ips(ip_rows),
        "top_identities": [
            {
                "identity": r["identity"],
                "count": int(r["n"]),
                "last_seen": r["last_seen"].isoformat() if r.get("last_seen") else None,
            }
            for r in identity_rows
        ],
    }


def admin_identity(user: dict) -> str:
    """How an admin is named in audit rows and ``created_by`` columns."""
    return f"admin:{user.get('email') or user['user_id']}"


def log_admin_action(request, user: dict, action: str, **detail) -> None:
    """Who did what to whom, from where, for a sensitive admin change."""
    log_event(
        "admin_action", outcome="success", request=request,
        user_id=user["user_id"],
        identity=admin_identity(user),
        detail={"action": action, **{k: v for k, v in detail.items() if v is not None}},
    )


def purge_old() -> int:
    """Drop events past retention. Returns rows removed."""
    cutoff = utc_now() - timedelta(days=get_settings().security_events_retention_days)
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM security_events WHERE ts < %s", (cutoff,))
        return cur.rowcount or 0


# What an account holder may see of their own ledger. A whitelist, so a type
# added later stays hidden until someone judges it safe. admin_action must never
# appear: it describes what an operator did, often to someone else.
USER_VISIBLE_EVENTS = (
    "login_success",
    "login_failed",
    "login_unverified",
    "register_success",
    "password_reset_requested",
    "password_reset_success",
    "password_reset_failed",
    "email_verified",
    "verify_failed",
    "verify_resend_requested",
    "session_revoked",
    "account_delete_failed",
    "account_deleted",
)


def _row_for_owner(row: dict) -> dict:
    """``detail`` can carry operator context and ``identity`` is whatever an
    attempt was made against; neither is the account holder's to read."""
    return {
        "ts": row["ts"].isoformat() if row.get("ts") else None,
        "event_type": row.get("event_type"),
        "outcome": row.get("outcome"),
        "ip": row.get("ip"),
        "user_agent": row.get("user_agent"),
    }


def list_events_for_user(user_id: int, limit: int = 50) -> List[dict]:
    """Newest-first whitelisted events of this account.

    Filtered on user_id alone: matching on identity too would let any user ask
    whether an address has an account, an enumeration oracle."""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT ts, event_type, outcome, ip, user_agent
            FROM security_events
            WHERE user_id = %s AND event_type = ANY(%s)
            ORDER BY ts DESC, id DESC
            LIMIT %s
            """,
            (user_id, list(USER_VISIBLE_EVENTS), limit),
        ).fetchall()
    return [_row_for_owner(dict(r)) for r in rows]


async def rate_limit_handler(request, exc):
    """A tripped limiter is the strongest flood signal there is, so it goes in the
    ledger before the voiced 429 goes out."""
    log_event("rate_limited", outcome="failure", request=request, detail={"path": request.url.path})
    return errors.rate_limited(request, exc)
