"""
Security event log — who tried to get in, what was denied, what an admin changed.

One append-only table (``security_events``) fed from the auth choke points in
account_engine.routes, the admin actions in account_engine.admin_routes, and the
slowapi 429 handler in api.py. Deliberately NOT fed by the site-wide login wall:
every bot probing the internet hits that wall, and logging it would drown the
table in noise within days — the auth endpoints (someone actively trying
credentials / invite codes) plus rate-limit hits carry the actual signal.

Writes are fire-and-forget: :func:`log_event` swallows every exception, so a
full disk / dropped DB can degrade the *log*, never a login. Reads power the
admin dashboard's Security tab (see admin_routes: /admin/security/*).

Privacy: raw client IPs and the *attempted* identity (email, or a mnemonic key
prefix — never the full key, never a password or token) are stored; the
scheduler prunes rows past ``SECURITY_EVENTS_RETENTION_DAYS`` (default 90), which
is the privacy mechanism for a private, members-only site.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional

from core.db_pool import get_connection, lock_schema_init

logger = logging.getLogger(__name__)

# Retention for the prune job (api.py schedules it with the other housekeeping).
RETENTION_DAYS = int(os.getenv("SECURITY_EVENTS_RETENTION_DAYS", "90"))

# Defensive field caps so a hostile client can't bloat rows via crafted inputs.
MAX_IDENTITY_LEN = 200
MAX_USER_AGENT_LEN = 300
MAX_DETAIL_LEN = 2000

# The event vocabulary, kept in one place so the dashboard and any future
# alerting agree on spelling. log_event accepts unknown types (forward-compat),
# but everything the backend emits today is listed here.
EVENT_TYPES = (
    "login_success",            # a session was issued (email or mnemonic)
    "login_failed",             # bad credentials / bad signature / unknown key
    "login_unverified",         # correct password, but the email isn't verified yet
    "register_success",         # an account was created
    "register_blocked",         # signup denied: email taken / key already registered
    "invite_invalid",           # wrong or already-used invite code
    "email_verified",           # a verification link was consumed
    "verify_failed",            # invalid/expired verification token
    "verify_resend_requested",  # someone asked for a new verification link
    "password_reset_requested", # someone started a password reset
    "password_reset_success",   # a reset token was consumed, password changed
    "password_reset_failed",    # invalid/expired reset token
    "rate_limited",             # slowapi tripped a 429 on an auth-adjacent path
    "admin_action",             # an admin changed users / invites / bridge keys
)

# outcome: 'success' for granted access / completed sensitive changes,
# 'failure' for every denial (the attack signal), 'info' for neutral events
# (reset requested, resend asked) that are worth a paper trail but deny nothing.
OUTCOMES = ("success", "failure", "info")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def client_ip(request) -> Optional[str]:
    """The real client IP. uvicorn runs with ``--proxy-headers``, so
    ``request.client.host`` is already the X-Forwarded-For client (same source
    of truth the rate limiter keys on — see core.rate_limit)."""
    try:
        return request.client.host if request and request.client else None
    except Exception:
        return None


def key_prefix(public_key: Optional[str]) -> Optional[str]:
    """A loggable handle for a mnemonic identity: the first 12 hex chars of the
    64-char public key. Enough to correlate repeat attempts, never the full key."""
    if not public_key:
        return None
    return f"{public_key[:12]}…"


def init_db() -> None:
    """Create the schema (idempotent, additive — safe on every replica).

    ``user_id`` deliberately has NO foreign key: the audit trail must survive
    the account it describes being deleted. ``ts`` is TIMESTAMPTZ (not the
    ISO-TEXT convention of the account tables) because the dashboard charts
    lean on ``date_trunc``/interval arithmetic."""
    with get_connection() as conn:
        lock_schema_init(conn)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS security_events (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
                event_type TEXT NOT NULL,
                outcome    TEXT NOT NULL DEFAULT 'info',
                user_id    BIGINT,
                identity   TEXT,
                ip         TEXT,
                user_agent TEXT,
                detail     TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_secevents_ts ON security_events(ts);
            CREATE INDEX IF NOT EXISTS idx_secevents_type_ts ON security_events(event_type, ts);
            """
        )


def _clip(value: Optional[str], cap: int) -> Optional[str]:
    if value is None:
        return None
    s = str(value).strip()
    if not s:
        return None
    return s[:cap]


def encode_detail(detail: Optional[dict]) -> Optional[str]:
    """Serialize the small structured context blob, dropping it (rather than the
    whole event) if it doesn't fit the cap or won't serialize."""
    if not detail:
        return None
    try:
        s = json.dumps(detail, ensure_ascii=False, default=str)
    except Exception:
        return None
    return s if len(s) <= MAX_DETAIL_LEN else None


def log_event(
    event_type: str,
    *,
    outcome: str = "info",
    request=None,
    user_id: Optional[int] = None,
    identity: Optional[str] = None,
    detail: Optional[dict] = None,
) -> None:
    """Record one security event. Fire-and-forget: never raises, never blocks a
    login on the log — a failed write is a warning in the app log and nothing else.

    Synchronous by design, matching how the account routes already call their
    store (single small INSERT per auth attempt; see AccountStore docstring)."""
    try:
        if outcome not in OUTCOMES:
            outcome = "info"
        user_agent = None
        if request is not None:
            try:
                user_agent = request.headers.get("user-agent")
            except Exception:
                user_agent = None
        with get_connection() as conn:
            conn.execute(
                """
                INSERT INTO security_events (event_type, outcome, user_id, identity, ip, user_agent, detail)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    _clip(event_type, 60) or "unknown",
                    outcome,
                    user_id,
                    _clip(identity, MAX_IDENTITY_LEN),
                    _clip(client_ip(request), 64),
                    _clip(user_agent, MAX_USER_AGENT_LEN),
                    encode_detail(detail),
                ),
            )
    except Exception as e:
        logger.warning(f"security event log failed ({event_type}): {e}")


# ---------------------------------------------------------------- dashboard reads
def _parse_detail(raw: Optional[str]):
    if not raw:
        return None
    try:
        return json.loads(raw)
    except Exception:
        return None


def _row_public(row: dict) -> dict:
    return {
        "id": row["id"],
        "ts": row["ts"].isoformat() if row.get("ts") else None,
        "event_type": row.get("event_type"),
        "outcome": row.get("outcome"),
        "user_id": row.get("user_id"),
        "identity": row.get("identity"),
        "ip": row.get("ip"),
        "user_agent": row.get("user_agent"),
        "detail": _parse_detail(row.get("detail")),
    }


def list_events(
    event_type: Optional[str] = None,
    outcome: Optional[str] = None,
    ip: Optional[str] = None,
    search: Optional[str] = None,
    hours: Optional[int] = None,
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """Filterable, newest-first page of the ledger for the dashboard table.
    ``search`` matches identity/IP substrings (case-insensitive)."""
    where: List[str] = []
    params: List = []
    if event_type:
        where.append("event_type = %s")
        params.append(event_type)
    if outcome:
        where.append("outcome = %s")
        params.append(outcome)
    if ip:
        where.append("ip = %s")
        params.append(ip)
    if search:
        where.append("(identity ILIKE %s OR ip ILIKE %s)")
        like = f"%{search}%"
        params.extend([like, like])
    if hours:
        where.append("ts >= %s")
        params.append(_now() - timedelta(hours=hours))
    clause = f"WHERE {' AND '.join(where)}" if where else ""

    with get_connection() as conn:
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM security_events {clause}", params
        ).fetchone()["n"]
        rows = conn.execute(
            f"""
            SELECT * FROM security_events {clause}
            ORDER BY ts DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            params + [limit, offset],
        ).fetchall()
    return {"total": total, "events": [_row_public(r) for r in rows]}


def zero_filled_series(rows: List[dict], days: int, today) -> List[dict]:
    """Fold (day, event_type, outcome, n) aggregate rows into one entry per
    calendar day over the window, oldest first, with missing days at zero — so
    the dashboard chart never has holes. Pure; unit-tested."""
    by_day: Dict[str, dict] = {}
    for offset in range(days - 1, -1, -1):
        day = (today - timedelta(days=offset)).isoformat()
        by_day[day] = {"day": day, "total": 0, "failures": 0, "by_type": {}}
    for r in rows:
        day = r["day"].isoformat() if hasattr(r["day"], "isoformat") else str(r["day"])
        slot = by_day.get(day)
        if slot is None:
            continue
        n = int(r["n"] or 0)
        slot["total"] += n
        if r["outcome"] == "failure":
            slot["failures"] += n
        slot["by_type"][r["event_type"]] = slot["by_type"].get(r["event_type"], 0) + n
    return list(by_day.values())


def fold_top_ips(rows: List[dict], limit: int = 10) -> List[dict]:
    """Fold (ip, event_type, n, last_seen) failure aggregates into a ranked
    top-offenders list with a per-type breakdown. Pure; unit-tested."""
    by_ip: Dict[str, dict] = {}
    for r in rows:
        ip = r.get("ip")
        if not ip:
            continue
        slot = by_ip.setdefault(ip, {"ip": ip, "count": 0, "last_seen": None, "types": {}})
        n = int(r["n"] or 0)
        slot["count"] += n
        slot["types"][r["event_type"]] = slot["types"].get(r["event_type"], 0) + n
        last = r.get("last_seen")
        last_iso = last.isoformat() if hasattr(last, "isoformat") else last
        if last_iso and (slot["last_seen"] is None or last_iso > slot["last_seen"]):
            slot["last_seen"] = last_iso
    ranked = sorted(by_ip.values(), key=lambda s: s["count"], reverse=True)
    return ranked[:limit]


def stats(days: int = 14) -> dict:
    """Everything the Security tab's metrics need in one payload: 24h tiles, a
    zero-filled per-day series, per-type totals, top offending IPs, and the
    most-targeted identities — all failure-centric, over the last ``days`` days."""
    days = max(1, min(days, 90))
    now = _now()
    since = now - timedelta(days=days - 1)
    day_start = since.replace(hour=0, minute=0, second=0, microsecond=0)
    last_24h = now - timedelta(hours=24)

    with get_connection() as conn:
        def tile(sql: str, params) -> int:
            return int(conn.execute(sql, params).fetchone()["n"] or 0)

        tiles = {
            "failed_logins_24h": tile(
                "SELECT COUNT(*) AS n FROM security_events WHERE ts >= %s AND event_type IN ('login_failed', 'login_unverified')",
                (last_24h,),
            ),
            "invite_rejections_24h": tile(
                "SELECT COUNT(*) AS n FROM security_events WHERE ts >= %s AND event_type = 'invite_invalid'",
                (last_24h,),
            ),
            "rate_limited_24h": tile(
                "SELECT COUNT(*) AS n FROM security_events WHERE ts >= %s AND event_type = 'rate_limited'",
                (last_24h,),
            ),
            "offending_ips_24h": tile(
                "SELECT COUNT(DISTINCT ip) AS n FROM security_events WHERE ts >= %s AND outcome = 'failure' AND ip IS NOT NULL",
                (last_24h,),
            ),
            "signups_window": tile(
                "SELECT COUNT(*) AS n FROM security_events WHERE ts >= %s AND event_type = 'register_success'",
                (day_start,),
            ),
            "events_window": tile(
                "SELECT COUNT(*) AS n FROM security_events WHERE ts >= %s", (day_start,)
            ),
        }

        series_rows = conn.execute(
            """
            SELECT date_trunc('day', ts)::date AS day, event_type, outcome, COUNT(*) AS n
            FROM security_events
            WHERE ts >= %s
            GROUP BY 1, 2, 3
            """,
            (day_start,),
        ).fetchall()

        type_rows = conn.execute(
            """
            SELECT event_type, outcome, COUNT(*) AS n
            FROM security_events
            WHERE ts >= %s
            GROUP BY 1, 2
            ORDER BY COUNT(*) DESC
            """,
            (day_start,),
        ).fetchall()

        ip_rows = conn.execute(
            """
            SELECT ip, event_type, COUNT(*) AS n, MAX(ts) AS last_seen
            FROM security_events
            WHERE ts >= %s AND outcome = 'failure' AND ip IS NOT NULL
            GROUP BY 1, 2
            """,
            (day_start,),
        ).fetchall()

        identity_rows = conn.execute(
            """
            SELECT identity, COUNT(*) AS n, MAX(ts) AS last_seen
            FROM security_events
            WHERE ts >= %s AND outcome = 'failure' AND identity IS NOT NULL
            GROUP BY 1
            ORDER BY COUNT(*) DESC
            LIMIT 8
            """,
            (day_start,),
        ).fetchall()

    return {
        "days": days,
        "retention_days": RETENTION_DAYS,
        "tiles": tiles,
        "series": zero_filled_series(series_rows, days, now.date()),
        "by_type": [
            {"event_type": r["event_type"], "outcome": r["outcome"], "count": int(r["n"])}
            for r in type_rows
        ],
        "top_ips": fold_top_ips(ip_rows),
        "top_identities": [
            {
                "identity": r["identity"],
                "count": int(r["n"]),
                "last_seen": r["last_seen"].isoformat() if r.get("last_seen") else None,
            }
            for r in identity_rows
        ],
    }


def purge_old(keep_days: int = RETENTION_DAYS) -> int:
    """Drop events past retention (housekeeping; scheduled in api.py alongside
    the session/challenge purge). Returns rows removed."""
    cutoff = _now() - timedelta(days=max(1, keep_days))
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM security_events WHERE ts < %s", (cutoff,))
        return cur.rowcount or 0
