"""
Account storage (PostgreSQL) — accounts, sessions, login challenges, favorites
and watch progress.

The account tables share one PostgreSQL database with the mapping tables (see
db_pool), but a Fribb resync only DELETEs the three mapping tables, so user data
is never touched by a sync — the historical reason these lived in a separate
SQLite file no longer applies. All access goes through the shared connection
pool (``db_pool.get_connection``).

Identity model (see account_engine.ed25519 / README): an account *is* an Ed25519
public key. The server stores only that public key — never the mnemonic, never a
password, never the private key. Possession is proven per-login by signing a
one-time challenge. Sessions are opaque random bearer tokens, stored only as a
SHA-256 hash so a DB leak can't be replayed.
"""

import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Tuple

from db_pool import get_connection, lock_schema_init

# Lifetimes.
SESSION_TTL = timedelta(days=30)
CHALLENGE_TTL = timedelta(minutes=5)
VERIFY_TOKEN_TTL = timedelta(hours=24)   # email verification link
RESET_TOKEN_TTL = timedelta(hours=1)     # password reset link

# Soft per-account row caps. An authenticated account can otherwise insert an
# unbounded number of distinct item_keys (one row each), bloating the DB. Updates
# to an existing key are always allowed; only growth past the cap is rejected.
MAX_FAVORITES_PER_USER = 2000
MAX_PROGRESS_PER_USER = 5000


class QuotaExceeded(Exception):
    """Raised when a per-account row cap would be exceeded (surfaced as HTTP 409)."""


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _hash_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


class AccountStore:
    """Thin PostgreSQL data layer for the account system.

    Methods are synchronous psycopg calls borrowing from the shared pool,
    matching the rest of this backend (api.py calls the DB synchronously from its
    async handlers via the thread pool); the volumes are tiny and per-request, so
    this is fine. Timestamps are kept as ISO-8601 ``TEXT`` so the lexicographic
    ``expires_at`` comparisons that gate sessions/challenges stay correct.
    """

    def __init__(self, db_path: Optional[str] = None):
        # db_path is retained for call-site compatibility but ignored: storage is
        # now the shared PostgreSQL pool, configured via DATABASE_URL (see db_pool).
        self._explicit_path = db_path

    # -- connection / schema --------------------------------------------
    def _connect(self):
        # Borrow a pooled connection (dict rows, transaction committed on exit).
        return get_connection()

    def init_db(self) -> None:
        """Create the schema (idempotent)."""
        with self._connect() as conn:
            # Serialize DDL across replicas (see db_pool.lock_schema_init).
            lock_schema_init(conn)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS accounts (
                    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    public_key    TEXT UNIQUE NOT NULL,
                    label         TEXT,
                    created_at    TEXT NOT NULL,
                    last_login_at TEXT
                );

                CREATE TABLE IF NOT EXISTS sessions (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

                -- Email+password identity. Added alongside the original Ed25519
                -- mnemonic identity (see module docstring): an account now has a
                -- public_key OR an email (or, in principle, both). public_key is
                -- therefore nullable, and the email columns are added in-place on
                -- already-deployed databases via the ALTERs below.
                ALTER TABLE accounts ALTER COLUMN public_key DROP NOT NULL;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email          TEXT;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_hash  TEXT;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
                -- Admin flag — gates the /admin dashboard (see admin_routes). Off by
                -- default; the first admin is seeded from ADMIN_EMAILS at startup
                -- (see bootstrap_admins) so the dashboard is reachable without
                -- hand-editing the database.
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_admin       BOOLEAN NOT NULL DEFAULT FALSE;
                -- Case-insensitive email uniqueness (NULLs — the crypto accounts —
                -- are allowed to coexist).
                CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email
                    ON accounts (LOWER(email)) WHERE email IS NOT NULL;

                -- One-time, single-use tokens emailed for verification / reset.
                -- Only the SHA-256 hash is stored (the raw token lives only in the
                -- link), mirroring how sessions are stored — a DB leak exposes no
                -- usable token.
                CREATE TABLE IF NOT EXISTS email_tokens (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    purpose    TEXT NOT NULL,   -- 'verify' | 'reset'
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_email_tokens_user ON email_tokens(user_id);

                CREATE TABLE IF NOT EXISTS challenges (
                    challenge  TEXT PRIMARY KEY,
                    public_key TEXT NOT NULL,
                    purpose    TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                -- Single-use invite tokens minted by the Discord bot (see
                -- discord_bot/). Unlike the shared, reusable SIGNUP_INVITE_CODE,
                -- each of these can register exactly ONE account: registration
                -- stamps used_at/used_by and a second attempt with the same code
                -- fails. Kept as a ledger (used rows are never auto-deleted) so the
                -- bot can show who consumed which invite.
                CREATE TABLE IF NOT EXISTS invite_tokens (
                    code        TEXT PRIMARY KEY,
                    created_by  TEXT,          -- discord user id that minted it
                    created_at  TEXT NOT NULL,
                    expires_at  TEXT,          -- NULL = never expires
                    used_at     TEXT,          -- NULL = still unused
                    used_by     TEXT           -- email that consumed it
                );
                CREATE INDEX IF NOT EXISTS idx_invite_tokens_unused ON invite_tokens(used_at);

                -- "favorites" doubles as the watchlists table: each row belongs to
                -- a named list (list_name). The original single-tab behaviour is just
                -- the default 'favorites' list, so legacy clients keep working. A show
                -- may appear in several lists at once, hence list_name is in the PK.
                CREATE TABLE IF NOT EXISTS favorites (
                    user_id       BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key      TEXT NOT NULL,
                    list_name     TEXT NOT NULL DEFAULT 'favorites',
                    tmdb_id       INTEGER,
                    anilist_id    INTEGER,
                    season_number INTEGER,
                    media_type    TEXT,
                    title         TEXT,
                    poster        TEXT,
                    added_at      TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key, list_name)
                );
                -- In-place upgrade for databases created before watchlists existed:
                -- add the column, then widen the primary key to include it (once).
                ALTER TABLE favorites ADD COLUMN IF NOT EXISTS list_name TEXT NOT NULL DEFAULT 'favorites';
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.key_column_usage
                        WHERE table_name = 'favorites'
                          AND constraint_name = 'favorites_pkey'
                          AND column_name = 'list_name'
                    ) THEN
                        ALTER TABLE favorites DROP CONSTRAINT IF EXISTS favorites_pkey;
                        ALTER TABLE favorites
                            ADD CONSTRAINT favorites_pkey PRIMARY KEY (user_id, item_key, list_name);
                    END IF;
                END $$;
                CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id, added_at);
                CREATE INDEX IF NOT EXISTS idx_favorites_list ON favorites(user_id, list_name, added_at);

                CREATE TABLE IF NOT EXISTS watch_progress (
                    user_id          BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key         TEXT NOT NULL,
                    tmdb_id          INTEGER,
                    anilist_id       INTEGER,
                    season_number    INTEGER,
                    episode_number   INTEGER,
                    position_seconds DOUBLE PRECISION,
                    duration_seconds DOUBLE PRECISION,
                    status           TEXT NOT NULL DEFAULT 'in_progress',
                    title            TEXT,
                    poster           TEXT,
                    media_type       TEXT,
                    updated_at       TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key)
                );
                -- In-place upgrade for DBs created before movies: lets a progress row
                -- carry 'movie' so history can route back to /watch-movie. Additive.
                ALTER TABLE watch_progress ADD COLUMN IF NOT EXISTS media_type TEXT;
                CREATE INDEX IF NOT EXISTS idx_progress_user ON watch_progress(user_id, updated_at);
                CREATE INDEX IF NOT EXISTS idx_progress_status ON watch_progress(user_id, status);
                """
            )
        self.purge_expired()
        print("[AccountStore] Schema ready (PostgreSQL).")

    # -- accounts -------------------------------------------------------
    def get_account_by_public_key(self, public_key: str) -> Optional[Dict]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE public_key = %s", (public_key,)
            ).fetchone()
            return dict(row) if row else None

    def get_account(self, user_id: int) -> Optional[Dict]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE user_id = %s", (user_id,)
            ).fetchone()
            return dict(row) if row else None

    def create_account(self, public_key: str, label: Optional[str]) -> Dict:
        """Create an account for a public key. Raises psycopg.errors.UniqueViolation
        if the key already exists."""
        with self._connect() as conn:
            row = conn.execute(
                "INSERT INTO accounts (public_key, label, created_at) VALUES (%s, %s, %s) RETURNING user_id",
                (public_key, label, _iso(_now())),
            ).fetchone()
            user_id = row["user_id"]
        return self.get_account(user_id)

    def touch_login(self, user_id: int) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET last_login_at = %s WHERE user_id = %s",
                (_iso(_now()), user_id),
            )

    # -- admin ----------------------------------------------------------
    def set_admin(self, user_id: int, is_admin: bool) -> None:
        """Flip an account's admin flag (used by the admin dashboard)."""
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET is_admin = %s WHERE user_id = %s",
                (is_admin, user_id),
            )

    def bootstrap_admins(self, emails: List[str]) -> int:
        """Promote the given emails to admin (idempotent). Seeds the first admin
        from ADMIN_EMAILS at startup so the dashboard is reachable without DB
        surgery; returns how many rows were newly promoted."""
        lowered = [e.strip().lower() for e in (emails or []) if e and e.strip()]
        if not lowered:
            return 0
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE accounts SET is_admin = TRUE"
                " WHERE LOWER(email) = ANY(%s) AND is_admin = FALSE",
                (lowered,),
            )
            return cur.rowcount

    def count_admins(self) -> int:
        with self._connect() as conn:
            return conn.execute(
                "SELECT COUNT(*) AS n FROM accounts WHERE is_admin = TRUE"
            ).fetchone()["n"]

    def delete_account(self, user_id: int) -> bool:
        """Delete an account and (via ON DELETE CASCADE) all its sessions,
        favorites, progress and email tokens. Returns False if it didn't exist."""
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM accounts WHERE user_id = %s", (user_id,))
            return cur.rowcount > 0

    def list_accounts(
        self, search: Optional[str] = None, limit: int = 50, offset: int = 0
    ) -> List[Dict]:
        """Accounts (newest first) with per-user favorite / progress / active-session
        counts, for the admin user table. Never returns password_hash. Optional
        case-insensitive search over email / label / numeric id."""
        params: list = []
        where = ""
        if search and search.strip():
            term = search.strip()
            like = f"%{term}%"
            where = (
                "WHERE a.email ILIKE %s OR a.label ILIKE %s"
                " OR CAST(a.user_id AS TEXT) = %s"
            )
            params += [like, like, term]
        now = _iso(_now())
        params += [now, limit, offset]
        with self._connect() as conn:
            rows = conn.execute(
                f"""
                SELECT a.user_id, a.email, a.label, a.email_verified, a.is_admin,
                       (a.public_key IS NOT NULL) AS has_mnemonic,
                       a.created_at, a.last_login_at,
                       (SELECT COUNT(*) FROM favorites f WHERE f.user_id = a.user_id) AS favorites_count,
                       (SELECT COUNT(*) FROM watch_progress w WHERE w.user_id = a.user_id) AS progress_count,
                       (SELECT COUNT(*) FROM sessions s WHERE s.user_id = a.user_id AND s.expires_at > %s) AS sessions_count
                FROM accounts a
                {where}
                ORDER BY a.created_at DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()
            return [dict(r) for r in rows]

    def count_accounts(self, search: Optional[str] = None) -> int:
        params: list = []
        where = ""
        if search and search.strip():
            term = search.strip()
            like = f"%{term}%"
            where = (
                "WHERE email ILIKE %s OR label ILIKE %s OR CAST(user_id AS TEXT) = %s"
            )
            params += [like, like, term]
        with self._connect() as conn:
            return conn.execute(
                f"SELECT COUNT(*) AS n FROM accounts {where}", tuple(params)
            ).fetchone()["n"]

    def admin_overview(self) -> Dict:
        """Aggregate account-system stats for the admin health dashboard."""
        with self._connect() as conn:
            def scalar(sql: str, p: tuple = ()) -> int:
                return conn.execute(sql, p).fetchone()["n"]

            now = _iso(_now())
            day_ago = _iso(_now() - timedelta(days=1))
            week_ago = _iso(_now() - timedelta(days=7))
            return {
                "users_total": scalar("SELECT COUNT(*) AS n FROM accounts"),
                "users_verified": scalar("SELECT COUNT(*) AS n FROM accounts WHERE email_verified = TRUE"),
                "users_admin": scalar("SELECT COUNT(*) AS n FROM accounts WHERE is_admin = TRUE"),
                "users_email": scalar("SELECT COUNT(*) AS n FROM accounts WHERE email IS NOT NULL"),
                "users_mnemonic": scalar("SELECT COUNT(*) AS n FROM accounts WHERE public_key IS NOT NULL"),
                "users_new_24h": scalar("SELECT COUNT(*) AS n FROM accounts WHERE created_at >= %s", (day_ago,)),
                "users_new_7d": scalar("SELECT COUNT(*) AS n FROM accounts WHERE created_at >= %s", (week_ago,)),
                "sessions_active": scalar("SELECT COUNT(*) AS n FROM sessions WHERE expires_at > %s", (now,)),
                "invites_total": scalar("SELECT COUNT(*) AS n FROM invite_tokens"),
                "invites_unused": scalar("SELECT COUNT(*) AS n FROM invite_tokens WHERE used_at IS NULL"),
                "invites_used": scalar("SELECT COUNT(*) AS n FROM invite_tokens WHERE used_at IS NOT NULL"),
                "favorites_total": scalar("SELECT COUNT(*) AS n FROM favorites"),
                "progress_total": scalar("SELECT COUNT(*) AS n FROM watch_progress"),
                "progress_completed": scalar("SELECT COUNT(*) AS n FROM watch_progress WHERE status = 'completed'"),
                "progress_in_progress": scalar("SELECT COUNT(*) AS n FROM watch_progress WHERE status = 'in_progress'"),
            }

    # -- email + password accounts --------------------------------------
    def get_account_by_email(self, email: str) -> Optional[Dict]:
        """Look up an account by email (case-insensitive)."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE LOWER(email) = LOWER(%s)", (email,)
            ).fetchone()
            return dict(row) if row else None

    def create_email_account(
        self, email: str, password_hash: str, label: Optional[str] = None
    ) -> Dict:
        """Create an email+password account (unverified). Raises
        psycopg.errors.UniqueViolation if the email is already taken."""
        with self._connect() as conn:
            row = conn.execute(
                """
                INSERT INTO accounts (email, password_hash, label, email_verified, created_at)
                VALUES (%s, %s, %s, FALSE, %s) RETURNING user_id
                """,
                (email, password_hash, label, _iso(_now())),
            ).fetchone()
            user_id = row["user_id"]
        return self.get_account(user_id)

    def set_password(self, user_id: int, password_hash: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET password_hash = %s WHERE user_id = %s",
                (password_hash, user_id),
            )

    def set_email_verified(self, user_id: int, verified: bool = True) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET email_verified = %s WHERE user_id = %s",
                (verified, user_id),
            )

    # -- email tokens (verification / password reset) -------------------
    def create_email_token(self, user_id: int, purpose: str, ttl: timedelta) -> str:
        """Issue a single-use token for ``purpose`` ('verify' | 'reset'). Returns
        the raw token (store only its hash). Any earlier token of the same purpose
        for this user is invalidated so only the newest link works."""
        raw = secrets.token_urlsafe(32)
        expires = _now() + ttl
        with self._connect() as conn:
            conn.execute(
                "DELETE FROM email_tokens WHERE user_id = %s AND purpose = %s",
                (user_id, purpose),
            )
            conn.execute(
                "INSERT INTO email_tokens (token_hash, user_id, purpose, created_at, expires_at)"
                " VALUES (%s, %s, %s, %s, %s)",
                (_hash_token(raw), user_id, purpose, _iso(_now()), _iso(expires)),
            )
        return raw

    def consume_email_token(self, raw_token: str, purpose: str) -> Optional[int]:
        """Atomically validate + delete a token. Returns the user_id on success,
        else None (unknown, wrong purpose, or expired). Single-use: the DELETE
        rowcount gates consumption so the same link can't be replayed."""
        if not raw_token:
            return None
        token_hash = _hash_token(raw_token)
        with self._connect() as conn:
            row = conn.execute(
                "SELECT user_id, purpose, expires_at FROM email_tokens WHERE token_hash = %s",
                (token_hash,),
            ).fetchone()
            if row is None:
                return None
            cur = conn.execute(
                "DELETE FROM email_tokens WHERE token_hash = %s", (token_hash,)
            )
            if cur.rowcount == 0 or row["purpose"] != purpose:
                return None
            try:
                if datetime.fromisoformat(row["expires_at"]) <= _now():
                    return None
            except ValueError:
                return None
            return row["user_id"]

    def revoke_user_sessions(self, user_id: int) -> None:
        """Drop every active session for an account (used after a password reset
        so a leaked session can't outlive the credential change)."""
        with self._connect() as conn:
            conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    # -- single-use invite tokens (minted by the Discord bot) -----------
    def create_invite_token(
        self, created_by: Optional[str] = None, ttl: Optional[timedelta] = None
    ) -> str:
        """Mint a fresh single-use invite code and return it. ``created_by`` is the
        Discord user id that requested it; ``ttl`` optionally expires the code (None
        => never expires, only single-use). The code is a short, copy-pasteable hex
        string the recipient types into the signup form's invite field."""
        code = secrets.token_hex(8)  # 16 hex chars — unguessable but easy to paste
        expires = _iso(_now() + ttl) if ttl else None
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO invite_tokens (code, created_by, created_at, expires_at)"
                " VALUES (%s, %s, %s, %s)",
                (code, created_by, _iso(_now()), expires),
            )
        return code

    def invite_token_is_available(self, code: str) -> bool:
        """True if ``code`` is a known invite token that is still unused and not
        expired. Read-only pre-check for a clean error message; consumption is
        gated authoritatively (and race-safely) by consume_invite_token."""
        if not code:
            return False
        with self._connect() as conn:
            row = conn.execute(
                "SELECT expires_at, used_at FROM invite_tokens WHERE code = %s", (code,)
            ).fetchone()
        if row is None or row["used_at"] is not None:
            return False
        if row["expires_at"]:
            try:
                if datetime.fromisoformat(row["expires_at"]) <= _now():
                    return False
            except ValueError:
                return False
        return True

    def consume_invite_token(self, code: str, used_by: Optional[str] = None) -> bool:
        """Atomically burn a single-use invite token. Returns True only if it
        existed, was unused, and had not expired. The ``used_at IS NULL`` guard in
        the UPDATE makes this race-safe: two concurrent signups with the same code
        contend on the row and only one UPDATE matches (rowcount 1)."""
        if not code:
            return False
        now = _iso(_now())
        with self._connect() as conn:
            cur = conn.execute(
                """
                UPDATE invite_tokens
                   SET used_at = %s, used_by = %s
                 WHERE code = %s
                   AND used_at IS NULL
                   AND (expires_at IS NULL OR expires_at > %s)
                """,
                (now, used_by, code, now),
            )
            return cur.rowcount > 0

    def list_invite_tokens(self, include_used: bool = False, limit: int = 50) -> List[Dict]:
        """Most-recently-minted invite tokens. By default only the unused ones
        (what the bot's 'list' command shows); include_used returns the full
        ledger."""
        with self._connect() as conn:
            if include_used:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens WHERE used_at IS NULL"
                    " ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            return [dict(r) for r in rows]

    def revoke_invite_token(self, code: str) -> bool:
        """Delete an UNUSED invite token (the bot's 'revoke' command). Returns
        False if the code is unknown or already used (used rows stay as a ledger)."""
        if not code:
            return False
        with self._connect() as conn:
            cur = conn.execute(
                "DELETE FROM invite_tokens WHERE code = %s AND used_at IS NULL", (code,)
            )
            return cur.rowcount > 0

    # -- challenges (one-time login nonces) -----------------------------
    def create_challenge(self, public_key: str, purpose: str) -> Tuple[str, str]:
        challenge = secrets.token_urlsafe(32)
        expires = _now() + CHALLENGE_TTL
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO challenges (challenge, public_key, purpose, expires_at) VALUES (%s, %s, %s, %s)",
                (challenge, public_key, purpose, _iso(expires)),
            )
        return challenge, _iso(expires)

    def consume_challenge(self, challenge: str, public_key: str, purpose: str) -> bool:
        """Atomically validate + delete a challenge. True only if it existed for
        this public key + purpose and had not expired (single use)."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT public_key, purpose, expires_at FROM challenges WHERE challenge = %s",
                (challenge,),
            ).fetchone()
            if row is None:
                return False
            # Always delete (single-use), even if it turns out invalid/expired.
            # Gate on rowcount: under concurrency two requests can both SELECT the
            # row, but only the transaction whose DELETE actually removes it (the
            # other races to 0 rows once the first commits) may consume it — so a
            # captured (pk, challenge, signature) can't be replayed in parallel.
            cur = conn.execute("DELETE FROM challenges WHERE challenge = %s", (challenge,))
            if cur.rowcount == 0:
                return False
            if row["public_key"] != public_key or row["purpose"] != purpose:
                return False
            try:
                expires = datetime.fromisoformat(row["expires_at"])
            except ValueError:
                return False
            return expires > _now()

    # -- sessions -------------------------------------------------------
    def create_session(self, user_id: int) -> Tuple[str, str]:
        """Issue a session. Returns (raw_token, expires_at_iso); only the hash is
        stored."""
        raw = secrets.token_urlsafe(32)
        expires = _now() + SESSION_TTL
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO sessions (token_hash, user_id, created_at, expires_at) VALUES (%s, %s, %s, %s)",
                (_hash_token(raw), user_id, _iso(_now()), _iso(expires)),
            )
        return raw, _iso(expires)

    def get_user_by_session(self, raw_token: str) -> Optional[Dict]:
        if not raw_token:
            return None
        with self._connect() as conn:
            row = conn.execute(
                """
                SELECT a.* , s.expires_at AS session_expires_at
                FROM sessions s JOIN accounts a ON a.user_id = s.user_id
                WHERE s.token_hash = %s
                """,
                (_hash_token(raw_token),),
            ).fetchone()
            if row is None:
                return None
            try:
                if datetime.fromisoformat(row["session_expires_at"]) <= _now():
                    conn.execute(
                        "DELETE FROM sessions WHERE token_hash = %s", (_hash_token(raw_token),)
                    )
                    return None
            except ValueError:
                return None
            return dict(row)

    def delete_session(self, raw_token: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "DELETE FROM sessions WHERE token_hash = %s", (_hash_token(raw_token),)
            )

    # -- favorites / watchlists -----------------------------------------
    # A "favorite" is a row in a named list (``list_name``). The default list is
    # 'favorites', which reproduces the original single-tab behaviour; any other
    # name is a custom watchlist (e.g. 'Todo', 'Done', 'Paused'). The same show
    # may live in several lists at once.
    def upsert_favorite(self, user_id: int, fav: Dict, list_name: str = "favorites") -> Dict:
        with self._connect() as conn:
            # Soft cap: reject only NEW keys past the limit; updates always pass.
            # Done in the same transaction as the insert so it's race-free enough
            # (a tiny concurrent overshoot is harmless for a storage guard). The cap
            # is per account across all lists.
            exists = conn.execute(
                "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_FAVORITES_PER_USER:
                    raise QuotaExceeded(f"favorites limit ({MAX_FAVORITES_PER_USER}) reached")
            conn.execute(
                """
                INSERT INTO favorites
                    (user_id, item_key, list_name, tmdb_id, anilist_id, season_number,
                     media_type, title, poster, added_at)
                VALUES (%(user_id)s, %(item_key)s, %(list_name)s, %(tmdb_id)s, %(anilist_id)s,
                        %(season_number)s, %(media_type)s, %(title)s, %(poster)s, %(added_at)s)
                ON CONFLICT(user_id, item_key, list_name) DO UPDATE SET
                    tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
                    season_number=excluded.season_number, media_type=excluded.media_type,
                    title=excluded.title, poster=excluded.poster
                """,
                {"user_id": user_id, "list_name": list_name, "added_at": _iso(_now()), **fav},
            )
            row = conn.execute(
                "SELECT * FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            return dict(row)

    def list_favorites(self, user_id: int, list_name: Optional[str] = None) -> List[Dict]:
        """Rows in one list, or every list (newest first) when ``list_name`` is None."""
        with self._connect() as conn:
            if list_name is None:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s ORDER BY added_at DESC",
                    (user_id,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s AND list_name = %s "
                    "ORDER BY added_at DESC",
                    (user_id, list_name),
                ).fetchall()
            return [dict(r) for r in rows]

    def list_watchlists(self, user_id: int) -> List[Dict]:
        """Distinct list names for a user with each list's item count."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT list_name, COUNT(*) AS count FROM favorites WHERE user_id = %s "
                "GROUP BY list_name ORDER BY list_name",
                (user_id,),
            ).fetchall()
            return [dict(r) for r in rows]

    def bulk_upsert_favorites(
        self, user_id: int, items: List[Tuple[str, Dict]]
    ) -> Dict:
        """Insert/update many favorites in a single transaction (for import).

        ``items`` is a list of ``(list_name, fav)`` pairs where ``fav`` carries
        item_key/tmdb_id/anilist_id/season_number/media_type/title/poster. New
        keys are inserted only while the per-account cap (across all lists) has
        room; keys that already exist always update (and don't count against the
        cap). Returns ``{"imported", "skipped_quota"}``."""
        imported = 0
        skipped_quota = 0
        now = _iso(_now())
        with self._connect() as conn:
            count = conn.execute(
                "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
            ).fetchone()["n"]
            for list_name, fav in items:
                exists = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, fav["item_key"], list_name),
                ).fetchone()
                if exists is None:
                    if count >= MAX_FAVORITES_PER_USER:
                        skipped_quota += 1
                        continue
                    count += 1
                conn.execute(
                    """
                    INSERT INTO favorites
                        (user_id, item_key, list_name, tmdb_id, anilist_id, season_number,
                         media_type, title, poster, added_at)
                    VALUES (%(user_id)s, %(item_key)s, %(list_name)s, %(tmdb_id)s, %(anilist_id)s,
                            %(season_number)s, %(media_type)s, %(title)s, %(poster)s, %(added_at)s)
                    ON CONFLICT(user_id, item_key, list_name) DO UPDATE SET
                        tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
                        season_number=excluded.season_number, media_type=excluded.media_type,
                        title=excluded.title, poster=excluded.poster
                    """,
                    {"user_id": user_id, "list_name": list_name, "added_at": now, **fav},
                )
                imported += 1
        return {"imported": imported, "skipped_quota": skipped_quota}

    def clear_favorites(self, user_id: int) -> int:
        """Delete every favorite in every list for a user (the 'replace' import
        mode clears first). Returns how many rows were removed."""
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM favorites WHERE user_id = %s", (user_id,))
            return cur.rowcount

    def remove_favorite(
        self, user_id: int, item_key: str, list_name: Optional[str] = None
    ) -> bool:
        """Remove a show from one list, or from every list when ``list_name`` is None."""
        with self._connect() as conn:
            if list_name is None:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s",
                    (user_id, item_key),
                )
            else:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, item_key, list_name),
                )
            return cur.rowcount > 0

    def is_favorite(
        self, user_id: int, item_key: str, list_name: Optional[str] = None
    ) -> bool:
        with self._connect() as conn:
            if list_name is None:
                row = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s",
                    (user_id, item_key),
                ).fetchone()
            else:
                row = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, item_key, list_name),
                ).fetchone()
            return row is not None

    # -- watch progress -------------------------------------------------
    def upsert_progress(self, user_id: int, prog: Dict) -> Dict:
        with self._connect() as conn:
            # Soft cap: reject only NEW keys past the limit; updates always pass
            # (same-episode progress saves keep working at the cap).
            exists = conn.execute(
                "SELECT 1 FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM watch_progress WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_PROGRESS_PER_USER:
                    raise QuotaExceeded(f"progress limit ({MAX_PROGRESS_PER_USER}) reached")
            conn.execute(
                """
                INSERT INTO watch_progress
                    (user_id, item_key, tmdb_id, anilist_id, season_number,
                     episode_number, position_seconds, duration_seconds, status,
                     title, poster, media_type, updated_at)
                VALUES (%(user_id)s, %(item_key)s, %(tmdb_id)s, %(anilist_id)s, %(season_number)s,
                        %(episode_number)s, %(position_seconds)s, %(duration_seconds)s, %(status)s,
                        %(title)s, %(poster)s, %(media_type)s, %(updated_at)s)
                ON CONFLICT(user_id, item_key) DO UPDATE SET
                    tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
                    season_number=excluded.season_number, episode_number=excluded.episode_number,
                    position_seconds=excluded.position_seconds, duration_seconds=excluded.duration_seconds,
                    status=excluded.status, title=excluded.title, poster=excluded.poster,
                    media_type=excluded.media_type, updated_at=excluded.updated_at
                """,
                {"user_id": user_id, "updated_at": _iso(_now()),
                 "media_type": None, **prog},
            )
            row = conn.execute(
                "SELECT * FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            return dict(row)

    def list_progress(self, user_id: int, status: Optional[str] = None) -> List[Dict]:
        with self._connect() as conn:
            if status:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s AND status = %s ORDER BY updated_at DESC",
                    (user_id, status),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s ORDER BY updated_at DESC",
                    (user_id,),
                ).fetchall()
            return [dict(r) for r in rows]

    def remove_progress(self, user_id: int, item_key: str) -> bool:
        with self._connect() as conn:
            cur = conn.execute(
                "DELETE FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, item_key),
            )
            return cur.rowcount > 0

    # -- maintenance ----------------------------------------------------
    def purge_expired(self) -> None:
        """Drop expired sessions + challenges (cheap housekeeping)."""
        now = _iso(_now())
        with self._connect() as conn:
            conn.execute("DELETE FROM sessions WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM challenges WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM email_tokens WHERE expires_at <= %s", (now,))
