"""Account storage: accounts, sessions, login challenges, email and invite
tokens, favorites (watchlists) and watch progress.

An account is either an Ed25519 public key (see ed25519.py) or an email with a
password hash. Session and email tokens are stored as SHA-256 hashes so a
database leak cannot be replayed. Timestamps are ISO-8601 TEXT in UTC, so the
``expires_at`` comparisons in SQL are plain string comparisons.
"""

import hashlib
import json
import logging
import secrets
from datetime import timedelta
from typing import Dict, List, Optional, Tuple

from core.clock import utc_now, utc_now_iso
from core.db_pool import get_connection, lock_schema_init

logger = logging.getLogger(__name__)

SESSION_TTL = timedelta(days=30)
CHALLENGE_TTL = timedelta(minutes=5)
VERIFY_TOKEN_TTL = timedelta(hours=24)
RESET_TOKEN_TTL = timedelta(hours=1)

# Soft caps: without them an account could insert unbounded distinct item_keys.
# Updates to existing keys always pass; only growth is capped.
MAX_FAVORITES_PER_USER = 2000
MAX_PROGRESS_PER_USER = 5000

# Three years, so Wrapped can look back two full years plus the current one
# without the table growing forever.
WATCH_EVENTS_RETENTION_DAYS = 3 * 365


class QuotaExceeded(Exception):
    """A per-account row cap would be exceeded (surfaced as HTTP 409)."""


def _hash_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _public_session_id(token_hash: str) -> str:
    """A stable handle for one session that is safe to put in a response.

    ``token_hash`` is the lookup key for a live bearer token and must never be
    published; a second, prefixed hash identifies the row without revealing it."""
    return hashlib.sha256(f"crimson-session:{token_hash}".encode("utf-8")).hexdigest()[:32]


def _account_search(search: Optional[str]) -> Tuple[str, list]:
    """WHERE clause over ``accounts a``, shared by the admin page and its total so
    the two can never disagree."""
    term = (search or "").strip()
    if not term:
        return "", []
    like = f"%{term}%"
    return (
        "WHERE a.email ILIKE %s OR a.label ILIKE %s OR a.username ILIKE %s"
        " OR CAST(a.user_id AS TEXT) = %s",
        [like, like, like, term],
    )


_FAVORITE_UPSERT = """
    INSERT INTO favorites
        (user_id, item_key, list_name, tmdb_id, anilist_id, season_number,
         media_type, title, poster, added_at)
    VALUES (%(user_id)s, %(item_key)s, %(list_name)s, %(tmdb_id)s, %(anilist_id)s,
            %(season_number)s, %(media_type)s, %(title)s, %(poster)s, %(added_at)s)
    ON CONFLICT(user_id, item_key, list_name) DO UPDATE SET
        tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
        season_number=excluded.season_number, media_type=excluded.media_type,
        title=excluded.title, poster=excluded.poster
"""


class AccountStore:
    """Synchronous psycopg calls off the shared pool; callers run them in a thread."""

    def init_db(self) -> None:
        with get_connection() as conn:
            lock_schema_init(conn)
            conn.execute(
                """
                -- An account has a public_key OR an email, so both are nullable.
                CREATE TABLE IF NOT EXISTS accounts (
                    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    public_key     TEXT UNIQUE,
                    label          TEXT,
                    created_at     TEXT NOT NULL,
                    last_login_at  TEXT,
                    email          TEXT,
                    password_hash  TEXT,
                    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
                    -- Seeded from ADMIN_EMAILS at startup (see bootstrap_admins).
                    is_admin       BOOLEAN NOT NULL DEFAULT FALSE,
                    -- JSON, so a new preference key is a frontend-only change.
                    preferences    TEXT,
                    -- Display name only: never used for auth, so not unique.
                    username       TEXT
                );
                -- NULL emails (mnemonic accounts) coexist.
                CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email
                    ON accounts (LOWER(email)) WHERE email IS NOT NULL;

                CREATE TABLE IF NOT EXISTS sessions (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

                CREATE TABLE IF NOT EXISTS email_tokens (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    purpose    TEXT NOT NULL,   -- 'verify' | 'reset'
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_email_tokens_user ON email_tokens(user_id);

                CREATE TABLE IF NOT EXISTS challenges (
                    challenge  TEXT PRIMARY KEY,
                    public_key TEXT NOT NULL,
                    purpose    TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                -- Single-use codes minted by the Discord bot. Used rows are kept
                -- as a ledger of who consumed which invite.
                CREATE TABLE IF NOT EXISTS invite_tokens (
                    code        TEXT PRIMARY KEY,
                    created_by  TEXT,          -- discord user id
                    created_at  TEXT NOT NULL,
                    expires_at  TEXT,          -- NULL = never expires
                    used_at     TEXT,          -- NULL = unused
                    used_by     TEXT           -- email that consumed it
                );
                CREATE INDEX IF NOT EXISTS idx_invite_tokens_unused ON invite_tokens(used_at);

                -- Also the watchlists table: 'favorites' is the default list and a
                -- show may sit in several lists, hence list_name in the key.
                CREATE TABLE IF NOT EXISTS favorites (
                    user_id       BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key      TEXT NOT NULL,
                    list_name     TEXT NOT NULL DEFAULT 'favorites',
                    tmdb_id       INTEGER,
                    anilist_id    INTEGER,
                    season_number INTEGER,
                    media_type    TEXT,
                    title         TEXT,
                    poster        TEXT,
                    added_at      TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key, list_name)
                );
                CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id, added_at);
                CREATE INDEX IF NOT EXISTS idx_favorites_list ON favorites(user_id, list_name, added_at);

                CREATE TABLE IF NOT EXISTS watch_progress (
                    user_id          BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key         TEXT NOT NULL,
                    tmdb_id          INTEGER,
                    anilist_id       INTEGER,
                    season_number    INTEGER,
                    episode_number   INTEGER,
                    position_seconds DOUBLE PRECISION,
                    duration_seconds DOUBLE PRECISION,
                    status           TEXT NOT NULL DEFAULT 'in_progress',
                    title            TEXT,
                    poster           TEXT,
                    -- 'movie' routes history back to /watch-movie.
                    media_type       TEXT,
                    -- Local media has no tmdb/anilist id, so its path token rides
                    -- here for /local/{local_id} and per-show dedup.
                    local_id         TEXT,
                    updated_at       TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key)
                );
                CREATE INDEX IF NOT EXISTS idx_progress_user ON watch_progress(user_id, updated_at);
                CREATE INDEX IF NOT EXISTS idx_progress_status ON watch_progress(user_id, status);
                """
            )
        self.purge_expired()
        logger.info("Account schema ready")

    def get_account_by_public_key(self, public_key: str) -> Optional[Dict]:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE public_key = %s", (public_key,)
            ).fetchone()
            return dict(row) if row else None

    def get_account(self, user_id: int) -> Optional[Dict]:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE user_id = %s", (user_id,)
            ).fetchone()
            return dict(row) if row else None

    def create_account(self, public_key: str, label: Optional[str]) -> Dict:
        """Create an account for a public key. Raises psycopg.errors.UniqueViolation
        if the key already exists."""
        with get_connection() as conn:
            row = conn.execute(
                "INSERT INTO accounts (public_key, label, created_at) VALUES (%s, %s, %s) RETURNING *",
                (public_key, label, utc_now_iso()),
            ).fetchone()
        return dict(row)

    def touch_login(self, user_id: int) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET last_login_at = %s WHERE user_id = %s",
                (utc_now_iso(), user_id),
            )

    def get_preferences(self, user_id: int) -> Dict:
        """Stored client preferences as a dict; ``{}`` when unset or unparseable."""
        with get_connection() as conn:
            row = conn.execute(
                "SELECT preferences FROM accounts WHERE user_id = %s", (user_id,)
            ).fetchone()
        if not row or not row.get("preferences"):
            return {}
        try:
            data = json.loads(row["preferences"])
        except (ValueError, TypeError):
            return {}
        return data if isinstance(data, dict) else {}

    def set_preferences(self, user_id: int, preferences: Dict) -> Dict:
        """Overwrite the account's preferences. Returns the stored dict."""
        blob = json.dumps(preferences, ensure_ascii=False)
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET preferences = %s WHERE user_id = %s",
                (blob, user_id),
            )
        return preferences

    def set_username(self, user_id: int, username: Optional[str]) -> None:
        """Set (or clear, with None) the account's cosmetic display name."""
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET username = %s WHERE user_id = %s",
                (username, user_id),
            )

    def set_admin(self, user_id: int, is_admin: bool) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET is_admin = %s WHERE user_id = %s",
                (is_admin, user_id),
            )

    def bootstrap_admins(self, emails: List[str]) -> int:
        """Promote the given emails to admin (idempotent). Returns how many rows
        were newly promoted."""
        lowered = [e.strip().lower() for e in (emails or []) if e and e.strip()]
        if not lowered:
            return 0
        with get_connection() as conn:
            cur = conn.execute(
                "UPDATE accounts SET is_admin = TRUE"
                " WHERE LOWER(email) = ANY(%s) AND is_admin = FALSE",
                (lowered,),
            )
            return cur.rowcount

    def count_admins(self) -> int:
        with get_connection() as conn:
            return conn.execute(
                "SELECT COUNT(*) AS n FROM accounts WHERE is_admin = TRUE"
            ).fetchone()["n"]

    def delete_account(self, user_id: int) -> bool:
        """Delete an account; ON DELETE CASCADE clears its rows. False if unknown."""
        with get_connection() as conn:
            cur = conn.execute("DELETE FROM accounts WHERE user_id = %s", (user_id,))
            return cur.rowcount > 0

    def wipe_demo_data(self) -> Dict[str, int]:
        """DEMO_MODE nightly reset. Admins survive because is_admin is only
        re-seeded at startup, so wiping them would lock the operator out."""
        with get_connection() as conn:
            accounts = conn.execute(
                "DELETE FROM accounts WHERE is_admin = FALSE"
            ).rowcount
            challenges = conn.execute("DELETE FROM challenges").rowcount
            invites = conn.execute("DELETE FROM invite_tokens").rowcount
        return {
            "accounts_deleted": accounts,
            "challenges_deleted": challenges,
            "invites_deleted": invites,
        }

    def list_accounts(
        self, search: Optional[str] = None, limit: int = 50, offset: int = 0
    ) -> List[Dict]:
        """The admin accounts table, newest first. Never returns password_hash."""
        where, params = _account_search(search)
        now = utc_now_iso()
        params += [now, limit, offset]
        with get_connection() as conn:
            rows = conn.execute(
                f"""
                SELECT a.user_id, a.email, a.label, a.username, a.email_verified, a.is_admin,
                       a.chat_enabled, a.chat_monthly_token_budget, a.music_enabled,
                       (a.public_key IS NOT NULL) AS has_mnemonic,
                       a.created_at, a.last_login_at,
                       (SELECT COUNT(*) FROM favorites f WHERE f.user_id = a.user_id) AS favorites_count,
                       (SELECT COUNT(*) FROM watch_progress w WHERE w.user_id = a.user_id) AS progress_count,
                       (SELECT COUNT(*) FROM sessions s WHERE s.user_id = a.user_id AND s.expires_at > %s) AS sessions_count
                FROM accounts a
                {where}
                ORDER BY a.created_at DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()
            return [dict(r) for r in rows]

    def count_accounts(self, search: Optional[str] = None) -> int:
        where, params = _account_search(search)
        with get_connection() as conn:
            return conn.execute(
                f"SELECT COUNT(*) AS n FROM accounts a {where}", tuple(params)
            ).fetchone()["n"]

    def email_recipients(self, verified_only: bool = True) -> List[Dict]:
        """Everyone an admin broadcast can reach. An unverified address may not
        belong to the account holder, hence ``verified_only``."""
        where = "email IS NOT NULL"
        if verified_only:
            where += " AND email_verified = TRUE"
        with get_connection() as conn:
            rows = conn.execute(
                f"SELECT user_id, email, username FROM accounts WHERE {where} ORDER BY user_id"
            ).fetchall()
            return [dict(r) for r in rows]

    def email_recipient_counts(self) -> Dict[str, int]:
        with get_connection() as conn:
            return dict(conn.execute(
                """
                SELECT COUNT(*) FILTER (WHERE email_verified = TRUE) AS verified,
                       COUNT(*) AS "all"
                FROM accounts WHERE email IS NOT NULL
                """
            ).fetchone())

    def admin_overview(self) -> Dict:
        """Account-system stats for the admin health dashboard."""
        now = utc_now()
        stats: Dict = {}
        with get_connection() as conn:
            stats.update(conn.execute(
                """
                SELECT COUNT(*)                                        AS users_total,
                       COUNT(*) FILTER (WHERE email_verified = TRUE)   AS users_verified,
                       COUNT(*) FILTER (WHERE is_admin = TRUE)         AS users_admin,
                       COUNT(*) FILTER (WHERE email IS NOT NULL)       AS users_email,
                       COUNT(*) FILTER (WHERE public_key IS NOT NULL)  AS users_mnemonic,
                       COUNT(*) FILTER (WHERE created_at >= %s)        AS users_new_24h,
                       COUNT(*) FILTER (WHERE created_at >= %s)        AS users_new_7d
                FROM accounts
                """,
                ((now - timedelta(days=1)).isoformat(), (now - timedelta(days=7)).isoformat()),
            ).fetchone())
            stats.update(conn.execute(
                "SELECT COUNT(*) AS sessions_active FROM sessions WHERE expires_at > %s",
                (now.isoformat(),),
            ).fetchone())
            stats.update(conn.execute(
                """
                SELECT COUNT(*)                                    AS invites_total,
                       COUNT(*) FILTER (WHERE used_at IS NULL)     AS invites_unused,
                       COUNT(*) FILTER (WHERE used_at IS NOT NULL) AS invites_used
                FROM invite_tokens
                """
            ).fetchone())
            stats.update(conn.execute(
                "SELECT COUNT(*) AS favorites_total FROM favorites"
            ).fetchone())
            stats.update(conn.execute(
                """
                SELECT COUNT(*)                                          AS progress_total,
                       COUNT(*) FILTER (WHERE status = 'completed')      AS progress_completed,
                       COUNT(*) FILTER (WHERE status = 'in_progress')    AS progress_in_progress
                FROM watch_progress
                """
            ).fetchone())
        return stats

    def get_account_by_email(self, email: str) -> Optional[Dict]:
        """Case-insensitive lookup by email."""
        with get_connection() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE LOWER(email) = LOWER(%s)", (email,)
            ).fetchone()
            return dict(row) if row else None

    def create_email_account(
        self, email: str, password_hash: str, label: Optional[str] = None
    ) -> Dict:
        """Create an email+password account (unverified). Raises
        psycopg.errors.UniqueViolation if the email is already taken."""
        with get_connection() as conn:
            row = conn.execute(
                """
                INSERT INTO accounts (email, password_hash, label, email_verified, created_at)
                VALUES (%s, %s, %s, FALSE, %s) RETURNING *
                """,
                (email, password_hash, label, utc_now_iso()),
            ).fetchone()
        return dict(row)

    def set_password(self, user_id: int, password_hash: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET password_hash = %s WHERE user_id = %s",
                (password_hash, user_id),
            )

    def set_email_verified(self, user_id: int, verified: bool = True) -> None:
        with get_connection() as conn:
            conn.execute(
                "UPDATE accounts SET email_verified = %s WHERE user_id = %s",
                (verified, user_id),
            )

    def create_email_token(self, user_id: int, purpose: str, ttl: timedelta) -> str:
        """Issue a raw single-use token. Earlier tokens of the same purpose are
        dropped so only the newest link works."""
        raw = secrets.token_urlsafe(32)
        expires = utc_now() + ttl
        with get_connection() as conn:
            conn.execute(
                "DELETE FROM email_tokens WHERE user_id = %s AND purpose = %s",
                (user_id, purpose),
            )
            conn.execute(
                "INSERT INTO email_tokens (token_hash, user_id, purpose, created_at, expires_at)"
                " VALUES (%s, %s, %s, %s, %s)",
                (_hash_token(raw), user_id, purpose, utc_now_iso(), expires.isoformat()),
            )
        return raw

    def consume_email_token(self, raw_token: str, purpose: str) -> Optional[int]:
        """Burn a token and return its user_id if it was for ``purpose`` and fresh.

        Any presented token is deleted, even a wrong or stale one, and only the
        request whose DELETE returned the row may use it, so a link cannot be
        replayed concurrently."""
        if not raw_token:
            return None
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM email_tokens WHERE token_hash = %s"
                " RETURNING user_id, purpose, expires_at",
                (_hash_token(raw_token),),
            ).fetchone()
        if row is None or row["purpose"] != purpose or row["expires_at"] <= utc_now_iso():
            return None
        return row["user_id"]

    def revoke_user_sessions(self, user_id: int) -> None:
        """Drop every session, so a leaked one can't outlive a password reset."""
        with get_connection() as conn:
            conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    def create_invite_tokens(
        self, count: int, created_by: Optional[str] = None, ttl: Optional[timedelta] = None
    ) -> List[str]:
        """Unguessable but short enough to paste. A ``ttl`` of None never expires."""
        codes = [secrets.token_hex(8) for _ in range(count)]
        now = utc_now()
        expires = (now + ttl).isoformat() if ttl else None
        with get_connection() as conn:
            conn.cursor().executemany(
                "INSERT INTO invite_tokens (code, created_by, created_at, expires_at) VALUES (%s, %s, %s, %s)",
                [(code, created_by, now.isoformat(), expires) for code in codes],
            )
        return codes

    def invite_token_is_available(self, code: str) -> bool:
        """Pre-check for a clean error message; consume_invite_token is the
        race-safe gate."""
        if not code:
            return False
        with get_connection() as conn:
            row = conn.execute(
                "SELECT expires_at, used_at FROM invite_tokens WHERE code = %s", (code,)
            ).fetchone()
        if row is None or row["used_at"] is not None:
            return False
        return not row["expires_at"] or row["expires_at"] > utc_now_iso()

    def consume_invite_token(self, code: str, used_by: Optional[str] = None) -> bool:
        """True only if the token existed, was unused and fresh. The ``used_at IS
        NULL`` guard makes it race-safe: only one concurrent UPDATE can match."""
        if not code:
            return False
        now = utc_now_iso()
        with get_connection() as conn:
            cur = conn.execute(
                """
                UPDATE invite_tokens
                   SET used_at = %s, used_by = %s
                 WHERE code = %s
                   AND used_at IS NULL
                   AND (expires_at IS NULL OR expires_at > %s)
                """,
                (now, used_by, code, now),
            )
            return cur.rowcount > 0

    def list_invite_tokens(self, include_used: bool = False, limit: int = 50) -> List[Dict]:
        """Newest invite tokens; unused only unless ``include_used``."""
        with get_connection() as conn:
            if include_used:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens WHERE used_at IS NULL"
                    " ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            return [dict(r) for r in rows]

    def revoke_invite_token(self, code: str) -> bool:
        """Delete an unused token. Used rows stay as the ledger."""
        if not code:
            return False
        with get_connection() as conn:
            cur = conn.execute(
                "DELETE FROM invite_tokens WHERE code = %s AND used_at IS NULL", (code,)
            )
            return cur.rowcount > 0

    def create_challenge(self, public_key: str, purpose: str) -> Tuple[str, str]:
        challenge = secrets.token_urlsafe(32)
        expires = utc_now() + CHALLENGE_TTL
        with get_connection() as conn:
            conn.execute(
                "INSERT INTO challenges (challenge, public_key, purpose, expires_at) VALUES (%s, %s, %s, %s)",
                (challenge, public_key, purpose, expires.isoformat()),
            )
        return challenge, expires.isoformat()

    def consume_challenge(self, challenge: str, public_key: str, purpose: str) -> bool:
        """Burn a challenge; True only if it matched and was fresh.

        Deleted unconditionally and gated on the returned row, so of two
        concurrent requests only one can consume it and a captured signature
        cannot be replayed in parallel."""
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM challenges WHERE challenge = %s"
                " RETURNING public_key, purpose, expires_at",
                (challenge,),
            ).fetchone()
        return (
            row is not None
            and row["public_key"] == public_key
            and row["purpose"] == purpose
            and row["expires_at"] > utc_now_iso()
        )

    def create_session(
        self, user_id: int,
        user_agent: Optional[str] = None, ip: Optional[str] = None,
    ) -> Tuple[str, str]:
        """Returns (raw_token, expires_at). The device columns let the owner
        recognise the session later."""
        raw = secrets.token_urlsafe(32)
        now = utc_now()
        expires = now + SESSION_TTL
        with get_connection() as conn:
            conn.execute(
                """
                INSERT INTO sessions (token_hash, user_id, created_at, expires_at,
                                      user_agent, ip, last_seen_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (_hash_token(raw), user_id, now.isoformat(), expires.isoformat(),
                 (user_agent or None), (ip or None), now.isoformat()),
            )
        return raw, expires.isoformat()

    def get_user_by_session(self, raw_token: str) -> Optional[Dict]:
        if not raw_token:
            return None
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT a.*, s.expires_at AS session_expires_at
                FROM sessions s JOIN accounts a ON a.user_id = s.user_id
                WHERE s.token_hash = %s AND s.expires_at > %s
                """,
                (_hash_token(raw_token), utc_now_iso()),
            ).fetchone()
        return dict(row) if row else None

    def delete_session(self, raw_token: str) -> None:
        with get_connection() as conn:
            conn.execute(
                "DELETE FROM sessions WHERE token_hash = %s", (_hash_token(raw_token),)
            )

    def validate_and_touch_session(self, raw_token: str) -> bool:
        """True iff the token names a live session, stamping last_seen_at.

        Called only on a login-wall cache miss, so this writes at most once per
        session per cache TTL, and doing it in the check costs no extra round trip."""
        if not raw_token:
            return False
        now = utc_now_iso()
        with get_connection() as conn:
            cur = conn.execute(
                "UPDATE sessions SET last_seen_at = %s"
                " WHERE token_hash = %s AND expires_at > %s",
                (now, _hash_token(raw_token), now),
            )
            return cur.rowcount > 0

    def list_sessions(self, user_id: int, current_token: Optional[str] = None) -> List[Dict]:
        """Live sessions, newest first, with the caller's flagged. The public id is
        derived here so a handler cannot leak ``token_hash`` by forwarding a row."""
        current_hash = _hash_token(current_token) if current_token else None
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT token_hash, created_at, expires_at, user_agent, ip, last_seen_at
                FROM sessions
                WHERE user_id = %s AND expires_at > %s
                ORDER BY created_at DESC
                """,
                (user_id, utc_now_iso()),
            ).fetchall()
        return [
            {
                "id": _public_session_id(r["token_hash"]),
                "created_at": r["created_at"],
                "expires_at": r["expires_at"],
                "last_seen_at": r["last_seen_at"],
                "user_agent": r["user_agent"],
                "ip": r["ip"],
                "current": current_hash is not None and r["token_hash"] == current_hash,
            }
            for r in rows
        ]

    def revoke_session(self, user_id: int, session_id: str) -> bool:
        """The public id is one-way, so it cannot become a WHERE clause: match it
        over this account's own rows, which also keeps it from being an oracle for
        another account's sessions."""
        with get_connection() as conn:
            rows = conn.execute(
                "SELECT token_hash FROM sessions WHERE user_id = %s", (user_id,)
            ).fetchall()
            for r in rows:
                if _public_session_id(r["token_hash"]) == session_id:
                    conn.execute(
                        "DELETE FROM sessions WHERE token_hash = %s", (r["token_hash"],)
                    )
                    return True
        return False

    def revoke_other_sessions(self, user_id: int, current_token: Optional[str]) -> int:
        """Sign out everywhere except the caller. Returns how many were dropped."""
        with get_connection() as conn:
            if current_token:
                cur = conn.execute(
                    "DELETE FROM sessions WHERE user_id = %s AND token_hash <> %s",
                    (user_id, _hash_token(current_token)),
                )
            else:
                cur = conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))
            return cur.rowcount

    def upsert_favorite(self, user_id: int, fav: Dict, list_name: str = "favorites") -> Dict:
        with get_connection() as conn:
            # A small concurrent overshoot of the cap is possible and harmless.
            exists = conn.execute(
                "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_FAVORITES_PER_USER:
                    raise QuotaExceeded(f"favorites limit ({MAX_FAVORITES_PER_USER}) reached")
            conn.execute(
                _FAVORITE_UPSERT,
                {"user_id": user_id, "list_name": list_name, "added_at": utc_now_iso(), **fav},
            )
            row = conn.execute(
                "SELECT * FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            return dict(row)

    def list_favorites(self, user_id: int, list_name: Optional[str] = None) -> List[Dict]:
        """Rows in one list, or every list (newest first) when ``list_name`` is None."""
        with get_connection() as conn:
            if list_name is None:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s ORDER BY added_at DESC",
                    (user_id,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s AND list_name = %s "
                    "ORDER BY added_at DESC",
                    (user_id, list_name),
                ).fetchall()
            return [dict(r) for r in rows]

    def library_counts(self, user_id: int) -> Dict[str, int]:
        with get_connection() as conn:
            return dict(conn.execute(
                """
                SELECT (SELECT COUNT(*) FROM favorites WHERE user_id = %s)      AS favorites,
                       (SELECT COUNT(*) FROM watch_progress WHERE user_id = %s) AS progress
                """,
                (user_id, user_id),
            ).fetchone())

    def list_watchlists(self, user_id: int) -> List[Dict]:
        """Distinct list names with each list's item count."""
        with get_connection() as conn:
            rows = conn.execute(
                "SELECT list_name, COUNT(*) AS count FROM favorites WHERE user_id = %s "
                "GROUP BY list_name ORDER BY list_name",
                (user_id,),
            ).fetchall()
            return [dict(r) for r in rows]

    def bulk_upsert_favorites(
        self, user_id: int, items: List[Tuple[str, Dict]], replace: bool = False
    ) -> Dict:
        """Import ``(list_name, fav)`` pairs in one transaction. New keys stop at
        the cap; existing keys always update. ``replace`` clears every list first in
        the same transaction, so a failed import never leaves the account empty."""
        imported = 0
        skipped_quota = 0
        now = utc_now_iso()
        with get_connection() as conn:
            if replace:
                conn.execute("DELETE FROM favorites WHERE user_id = %s", (user_id,))
            count = conn.execute(
                "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
            ).fetchone()["n"]
            for list_name, fav in items:
                exists = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, fav["item_key"], list_name),
                ).fetchone()
                if exists is None:
                    if count >= MAX_FAVORITES_PER_USER:
                        skipped_quota += 1
                        continue
                    count += 1
                conn.execute(
                    _FAVORITE_UPSERT,
                    {"user_id": user_id, "list_name": list_name, "added_at": now, **fav},
                )
                imported += 1
        return {"imported": imported, "skipped_quota": skipped_quota}

    def remove_favorite(
        self, user_id: int, item_key: str, list_name: Optional[str] = None
    ) -> bool:
        """Remove a show from one list, or from every list when ``list_name`` is None."""
        with get_connection() as conn:
            if list_name is None:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s",
                    (user_id, item_key),
                )
            else:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, item_key, list_name),
                )
            return cur.rowcount > 0

    def upsert_progress(self, user_id: int, prog: Dict) -> Dict:
        with get_connection() as conn:
            exists = conn.execute(
                "SELECT 1 FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM watch_progress WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_PROGRESS_PER_USER:
                    raise QuotaExceeded(f"progress limit ({MAX_PROGRESS_PER_USER}) reached")
            conn.execute(
                """
                INSERT INTO watch_progress
                    (user_id, item_key, tmdb_id, anilist_id, season_number,
                     episode_number, position_seconds, duration_seconds, status,
                     title, poster, media_type, local_id, updated_at)
                VALUES (%(user_id)s, %(item_key)s, %(tmdb_id)s, %(anilist_id)s, %(season_number)s,
                        %(episode_number)s, %(position_seconds)s, %(duration_seconds)s, %(status)s,
                        %(title)s, %(poster)s, %(media_type)s, %(local_id)s, %(updated_at)s)
                ON CONFLICT(user_id, item_key) DO UPDATE SET
                    tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
                    season_number=excluded.season_number, episode_number=excluded.episode_number,
                    position_seconds=excluded.position_seconds, duration_seconds=excluded.duration_seconds,
                    status=excluded.status, title=excluded.title, poster=excluded.poster,
                    media_type=excluded.media_type, local_id=excluded.local_id, updated_at=excluded.updated_at
                """,
                {"user_id": user_id, "updated_at": utc_now_iso(),
                 "media_type": None, "local_id": None, **prog},
            )
            # watch_progress is overwritten on a timer, so it cannot say when
            # anything was watched; watch_events can. Same connection on purpose:
            # this save fires every 30s per viewer, so an extra round trip is not free.
            conn.execute(
                """
                INSERT INTO watch_events
                    (user_id, item_key, watched_on, anilist_id, tmdb_id, media_type, title, seconds)
                VALUES (%(user_id)s, %(item_key)s, (now() AT TIME ZONE 'utc')::date,
                        %(anilist_id)s, %(tmdb_id)s, %(media_type)s, %(title)s, %(position_seconds)s)
                ON CONFLICT (user_id, item_key, watched_on) DO UPDATE SET
                    -- A rewatch restarts at zero, so only the max never shrinks.
                    seconds = GREATEST(COALESCE(watch_events.seconds, 0),
                                       COALESCE(excluded.seconds, 0)),
                    title = COALESCE(excluded.title, watch_events.title)
                """,
                {"user_id": user_id, "item_key": prog["item_key"],
                 "anilist_id": prog.get("anilist_id"), "tmdb_id": prog.get("tmdb_id"),
                 "media_type": prog.get("media_type"), "title": prog.get("title"),
                 "position_seconds": prog.get("position_seconds")},
            )

            row = conn.execute(
                "SELECT * FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            return dict(row)

    def list_progress(self, user_id: int, status: Optional[str] = None) -> List[Dict]:
        with get_connection() as conn:
            if status:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s AND status = %s ORDER BY updated_at DESC",
                    (user_id, status),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s ORDER BY updated_at DESC",
                    (user_id,),
                ).fetchall()
            return [dict(r) for r in rows]

    def remove_progress(self, user_id: int, item_key: str) -> bool:
        with get_connection() as conn:
            cur = conn.execute(
                "DELETE FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, item_key),
            )
            return cur.rowcount > 0

    def purge_expired(self) -> None:
        """Drop expired sessions, challenges, email tokens and old watch events."""
        now = utc_now_iso()
        with get_connection() as conn:
            conn.execute("DELETE FROM sessions WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM challenges WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM email_tokens WHERE expires_at <= %s", (now,))
            # init_db() runs before the migration runner, so on a fresh install
            # watch_events (migration 006) does not exist yet, and a failed DELETE
            # would abort this shared transaction.
            if conn.execute("SELECT to_regclass('public.watch_events') AS t").fetchone()["t"]:
                conn.execute(
                    "DELETE FROM watch_events WHERE watched_on < %s",
                    ((utc_now() - timedelta(days=WATCH_EVENTS_RETENTION_DAYS)).date(),),
                )


store = AccountStore()
