"""
Account storage (PostgreSQL): accounts, sessions, login challenges, favorites
and watch progress. Shares the mapping tables' database (see db_pool), but a
Fribb resync only touches the mapping tables, so user data survives it.

Identity model (see account_engine.ed25519): an account *is* an Ed25519 public
key. Only the public key is stored, never the mnemonic or private key, and
possession is proven per-login by signing a one-time challenge. Session tokens
are stored as SHA-256 hashes so a DB leak can't be replayed.
"""

import hashlib
import json
import secrets
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Tuple

from core.db_pool import get_connection, lock_schema_init

# Lifetimes.
SESSION_TTL = timedelta(days=30)
CHALLENGE_TTL = timedelta(minutes=5)
VERIFY_TOKEN_TTL = timedelta(hours=24)   # email verification link
RESET_TOKEN_TTL = timedelta(hours=1)     # password reset link

# Soft per-account row caps: an account could otherwise insert unbounded
# distinct item_keys. Updates to existing keys pass; only growth is capped.
MAX_FAVORITES_PER_USER = 2000
MAX_PROGRESS_PER_USER = 5000

# How long a watch event is kept. Three years, so Wrapped can look back two full
# years and still have the current one, and so the one table here designed to be
# read years later is not also the one that grows forever.
WATCH_EVENTS_RETENTION_DAYS = 3 * 365


class QuotaExceeded(Exception):
    """Raised when a per-account row cap would be exceeded (surfaced as HTTP 409)."""


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _hash_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _public_session_id(token_hash: str) -> str:
    """A stable handle for one session that is safe to put in a response.

    ``token_hash`` is the primary key and the obvious identifier, and it is the
    one value that must never be published: it is the SHA-256 of a live bearer
    token, so handing it out hands out the lookup key for the session table.
    Hashing it again with a distinct prefix gives a stable id that identifies the
    row for revocation without being reversible to the key."""
    return hashlib.sha256(f"crimson-session:{token_hash}".encode("utf-8")).hexdigest()[:32]


def _account_search(search: Optional[str]) -> Tuple[str, list]:
    """The admin table's WHERE clause over ``accounts a``, shared by the page and
    its total so the two can never disagree."""
    term = (search or "").strip()
    if not term:
        return "", []
    like = f"%{term}%"
    return (
        "WHERE a.email ILIKE %s OR a.label ILIKE %s OR a.username ILIKE %s"
        " OR CAST(a.user_id AS TEXT) = %s",
        [like, like, like, term],
    )


_FAVORITE_UPSERT = """
    INSERT INTO favorites
        (user_id, item_key, list_name, tmdb_id, anilist_id, season_number,
         media_type, title, poster, added_at)
    VALUES (%(user_id)s, %(item_key)s, %(list_name)s, %(tmdb_id)s, %(anilist_id)s,
            %(season_number)s, %(media_type)s, %(title)s, %(poster)s, %(added_at)s)
    ON CONFLICT(user_id, item_key, list_name) DO UPDATE SET
        tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
        season_number=excluded.season_number, media_type=excluded.media_type,
        title=excluded.title, poster=excluded.poster
"""


class AccountStore:
    """Thin PostgreSQL data layer for the account system.

    Methods are synchronous psycopg calls off the shared pool; callers run them in
    a thread pool. Timestamps are ISO-8601 ``TEXT`` so the lexicographic
    ``expires_at`` comparisons gating sessions and challenges stay correct.
    """

    def __init__(self, db_path: Optional[str] = None):
        # Ignored; kept for call-site compatibility. Storage is the shared pool.
        self._explicit_path = db_path

    # -- connection / schema --------------------------------------------
    def _connect(self):
        # Pooled connection: dict rows, commits on exit.
        return get_connection()

    def init_db(self) -> None:
        """Create the schema (idempotent)."""
        with self._connect() as conn:
            # Serialize DDL across replicas (see db_pool.lock_schema_init).
            lock_schema_init(conn)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS accounts (
                    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    public_key    TEXT UNIQUE NOT NULL,
                    label         TEXT,
                    created_at    TEXT NOT NULL,
                    last_login_at TEXT
                );

                CREATE TABLE IF NOT EXISTS sessions (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

                -- Email+password identity alongside the Ed25519 one: an account
                -- has a public_key OR an email, so public_key is nullable. The
                -- ALTERs upgrade already-deployed databases in place.
                ALTER TABLE accounts ALTER COLUMN public_key DROP NOT NULL;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email          TEXT;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS password_hash  TEXT;
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
                -- Gates the /admin dashboard. The first admin is seeded from
                -- ADMIN_EMAILS at startup (see bootstrap_admins).
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_admin       BOOLEAN NOT NULL DEFAULT FALSE;
                -- Client preferences as JSON in TEXT, so a new preference key is a
                -- frontend-only change. NULL => the client uses its local default.
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS preferences    TEXT;
                -- Cosmetic display name. Never used for auth, and non-unique on
                -- purpose: it is a display name, not an identity.
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS username       TEXT;
                -- Case-insensitive email uniqueness; NULLs (crypto accounts) coexist.
                CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email
                    ON accounts (LOWER(email)) WHERE email IS NOT NULL;

                -- Single-use tokens emailed for verification / reset. Only the
                -- SHA-256 hash is stored, so a DB leak exposes no usable token.
                CREATE TABLE IF NOT EXISTS email_tokens (
                    token_hash TEXT PRIMARY KEY,
                    user_id    BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    purpose    TEXT NOT NULL,   -- 'verify' | 'reset'
                    created_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_email_tokens_user ON email_tokens(user_id);

                CREATE TABLE IF NOT EXISTS challenges (
                    challenge  TEXT PRIMARY KEY,
                    public_key TEXT NOT NULL,
                    purpose    TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );

                -- Single-use invite tokens minted by the Discord bot. Unlike the
                -- reusable SIGNUP_INVITE_CODE each registers exactly one account.
                -- Used rows are kept as a ledger of who consumed which invite.
                CREATE TABLE IF NOT EXISTS invite_tokens (
                    code        TEXT PRIMARY KEY,
                    created_by  TEXT,          -- discord user id that minted it
                    created_at  TEXT NOT NULL,
                    expires_at  TEXT,          -- NULL = never expires
                    used_at     TEXT,          -- NULL = still unused
                    used_by     TEXT           -- email that consumed it
                );
                CREATE INDEX IF NOT EXISTS idx_invite_tokens_unused ON invite_tokens(used_at);

                -- Doubles as the watchlists table: each row belongs to a named list,
                -- defaulting to 'favorites' so legacy clients keep working. A show may
                -- sit in several lists, hence list_name in the primary key.
                CREATE TABLE IF NOT EXISTS favorites (
                    user_id       BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key      TEXT NOT NULL,
                    list_name     TEXT NOT NULL DEFAULT 'favorites',
                    tmdb_id       INTEGER,
                    anilist_id    INTEGER,
                    season_number INTEGER,
                    media_type    TEXT,
                    title         TEXT,
                    poster        TEXT,
                    added_at      TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key, list_name)
                );
                -- In-place upgrade for pre-watchlist databases: add the column,
                -- then widen the primary key to include it (once).
                ALTER TABLE favorites ADD COLUMN IF NOT EXISTS list_name TEXT NOT NULL DEFAULT 'favorites';
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.key_column_usage
                        WHERE table_name = 'favorites'
                          AND constraint_name = 'favorites_pkey'
                          AND column_name = 'list_name'
                    ) THEN
                        ALTER TABLE favorites DROP CONSTRAINT IF EXISTS favorites_pkey;
                        ALTER TABLE favorites
                            ADD CONSTRAINT favorites_pkey PRIMARY KEY (user_id, item_key, list_name);
                    END IF;
                END $$;
                CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id, added_at);
                CREATE INDEX IF NOT EXISTS idx_favorites_list ON favorites(user_id, list_name, added_at);

                CREATE TABLE IF NOT EXISTS watch_progress (
                    user_id          BIGINT NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
                    item_key         TEXT NOT NULL,
                    tmdb_id          INTEGER,
                    anilist_id       INTEGER,
                    season_number    INTEGER,
                    episode_number   INTEGER,
                    position_seconds DOUBLE PRECISION,
                    duration_seconds DOUBLE PRECISION,
                    status           TEXT NOT NULL DEFAULT 'in_progress',
                    title            TEXT,
                    poster           TEXT,
                    media_type       TEXT,
                    local_id         TEXT,
                    updated_at       TEXT NOT NULL,
                    PRIMARY KEY (user_id, item_key)
                );
                -- Pre-movies upgrade: lets a row carry 'movie' so history can route
                -- back to /watch-movie.
                ALTER TABLE watch_progress ADD COLUMN IF NOT EXISTS media_type TEXT;
                -- Local media has no tmdb/anilist id, so the on-disk path token rides
                -- here: history routes to /local/{local_id} and the title's episodes
                -- dedup as one show.
                ALTER TABLE watch_progress ADD COLUMN IF NOT EXISTS local_id TEXT;
                CREATE INDEX IF NOT EXISTS idx_progress_user ON watch_progress(user_id, updated_at);
                CREATE INDEX IF NOT EXISTS idx_progress_status ON watch_progress(user_id, status);
                """
            )
        self.purge_expired()
        print("[AccountStore] Schema ready (PostgreSQL).")

    # -- accounts -------------------------------------------------------
    def get_account_by_public_key(self, public_key: str) -> Optional[Dict]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE public_key = %s", (public_key,)
            ).fetchone()
            return dict(row) if row else None

    def get_account(self, user_id: int) -> Optional[Dict]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE user_id = %s", (user_id,)
            ).fetchone()
            return dict(row) if row else None

    def create_account(self, public_key: str, label: Optional[str]) -> Dict:
        """Create an account for a public key. Raises psycopg.errors.UniqueViolation
        if the key already exists."""
        with self._connect() as conn:
            row = conn.execute(
                "INSERT INTO accounts (public_key, label, created_at) VALUES (%s, %s, %s) RETURNING user_id",
                (public_key, label, _iso(_now())),
            ).fetchone()
            user_id = row["user_id"]
        return self.get_account(user_id)

    def touch_login(self, user_id: int) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET last_login_at = %s WHERE user_id = %s",
                (_iso(_now()), user_id),
            )

    # -- preferences ----------------------------------------------------
    def get_preferences(self, user_id: int) -> Dict:
        """Stored client preferences as a dict; ``{}`` when unset or unparseable."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT preferences FROM accounts WHERE user_id = %s", (user_id,)
            ).fetchone()
        if not row or not row.get("preferences"):
            return {}
        try:
            data = json.loads(row["preferences"])
        except (ValueError, TypeError):
            return {}
        return data if isinstance(data, dict) else {}

    def set_preferences(self, user_id: int, preferences: Dict) -> Dict:
        """Overwrite the account's preferences. Returns the stored dict."""
        blob = json.dumps(preferences, ensure_ascii=False)
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET preferences = %s WHERE user_id = %s",
                (blob, user_id),
            )
        return preferences

    # -- display name ---------------------------------------------------
    def set_username(self, user_id: int, username: Optional[str]) -> None:
        """Set (or clear, with None) the account's cosmetic display name."""
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET username = %s WHERE user_id = %s",
                (username, user_id),
            )

    # -- admin ----------------------------------------------------------
    def set_admin(self, user_id: int, is_admin: bool) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET is_admin = %s WHERE user_id = %s",
                (is_admin, user_id),
            )

    def bootstrap_admins(self, emails: List[str]) -> int:
        """Promote the given emails to admin (idempotent). Returns how many rows
        were newly promoted."""
        lowered = [e.strip().lower() for e in (emails or []) if e and e.strip()]
        if not lowered:
            return 0
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE accounts SET is_admin = TRUE"
                " WHERE LOWER(email) = ANY(%s) AND is_admin = FALSE",
                (lowered,),
            )
            return cur.rowcount

    def count_admins(self) -> int:
        with self._connect() as conn:
            return conn.execute(
                "SELECT COUNT(*) AS n FROM accounts WHERE is_admin = TRUE"
            ).fetchone()["n"]

    def delete_account(self, user_id: int) -> bool:
        """Delete an account; ON DELETE CASCADE clears its rows. False if unknown."""
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM accounts WHERE user_id = %s", (user_id,))
            return cur.rowcount > 0

    def wipe_demo_data(self) -> Dict[str, int]:
        """DEMO_MODE nightly reset: delete every non-admin account (cascading its
        rows), plus all challenges and invite tokens. Admins are preserved because
        is_admin is only re-seeded at startup, so wiping them would lock the
        operator out until a restart. Returns row counts for logging."""
        with self._connect() as conn:
            accounts = conn.execute(
                "DELETE FROM accounts WHERE is_admin = FALSE"
            ).rowcount
            challenges = conn.execute("DELETE FROM challenges").rowcount
            invites = conn.execute("DELETE FROM invite_tokens").rowcount
        return {
            "accounts_deleted": accounts,
            "challenges_deleted": challenges,
            "invites_deleted": invites,
        }

    def list_accounts(
        self, search: Optional[str] = None, limit: int = 50, offset: int = 0
    ) -> List[Dict]:
        """Accounts (newest first) with favorite / progress / session counts for the
        admin table. Never returns password_hash. Search is case-insensitive over
        email, label, display name and numeric id."""
        where, params = _account_search(search)
        now = _iso(_now())
        params += [now, limit, offset]
        with self._connect() as conn:
            rows = conn.execute(
                f"""
                SELECT a.user_id, a.email, a.label, a.username, a.email_verified, a.is_admin,
                       a.chat_enabled, a.chat_monthly_token_budget,
                       (a.public_key IS NOT NULL) AS has_mnemonic,
                       a.created_at, a.last_login_at,
                       (SELECT COUNT(*) FROM favorites f WHERE f.user_id = a.user_id) AS favorites_count,
                       (SELECT COUNT(*) FROM watch_progress w WHERE w.user_id = a.user_id) AS progress_count,
                       (SELECT COUNT(*) FROM sessions s WHERE s.user_id = a.user_id AND s.expires_at > %s) AS sessions_count
                FROM accounts a
                {where}
                ORDER BY a.created_at DESC
                LIMIT %s OFFSET %s
                """,
                tuple(params),
            ).fetchall()
            return [dict(r) for r in rows]

    def count_accounts(self, search: Optional[str] = None) -> int:
        where, params = _account_search(search)
        with self._connect() as conn:
            return conn.execute(
                f"SELECT COUNT(*) AS n FROM accounts a {where}", tuple(params)
            ).fetchone()["n"]

    def email_recipients(self, verified_only: bool = True) -> List[Dict]:
        """Everyone an admin broadcast can reach; mnemonic-only accounts have no
        address and are skipped. ``verified_only`` also drops unverified addresses,
        which may not belong to the account holder."""
        where = "email IS NOT NULL"
        if verified_only:
            where += " AND email_verified = TRUE"
        with self._connect() as conn:
            rows = conn.execute(
                f"SELECT user_id, email, username FROM accounts WHERE {where} ORDER BY user_id"
            ).fetchall()
            return [dict(r) for r in rows]

    def admin_overview(self) -> Dict:
        """Aggregate account-system stats for the admin health dashboard."""
        with self._connect() as conn:
            def scalar(sql: str, p: tuple = ()) -> int:
                return conn.execute(sql, p).fetchone()["n"]

            now = _iso(_now())
            day_ago = _iso(_now() - timedelta(days=1))
            week_ago = _iso(_now() - timedelta(days=7))
            return {
                "users_total": scalar("SELECT COUNT(*) AS n FROM accounts"),
                "users_verified": scalar("SELECT COUNT(*) AS n FROM accounts WHERE email_verified = TRUE"),
                "users_admin": scalar("SELECT COUNT(*) AS n FROM accounts WHERE is_admin = TRUE"),
                "users_email": scalar("SELECT COUNT(*) AS n FROM accounts WHERE email IS NOT NULL"),
                "users_mnemonic": scalar("SELECT COUNT(*) AS n FROM accounts WHERE public_key IS NOT NULL"),
                "users_new_24h": scalar("SELECT COUNT(*) AS n FROM accounts WHERE created_at >= %s", (day_ago,)),
                "users_new_7d": scalar("SELECT COUNT(*) AS n FROM accounts WHERE created_at >= %s", (week_ago,)),
                "sessions_active": scalar("SELECT COUNT(*) AS n FROM sessions WHERE expires_at > %s", (now,)),
                "invites_total": scalar("SELECT COUNT(*) AS n FROM invite_tokens"),
                "invites_unused": scalar("SELECT COUNT(*) AS n FROM invite_tokens WHERE used_at IS NULL"),
                "invites_used": scalar("SELECT COUNT(*) AS n FROM invite_tokens WHERE used_at IS NOT NULL"),
                "favorites_total": scalar("SELECT COUNT(*) AS n FROM favorites"),
                "progress_total": scalar("SELECT COUNT(*) AS n FROM watch_progress"),
                "progress_completed": scalar("SELECT COUNT(*) AS n FROM watch_progress WHERE status = 'completed'"),
                "progress_in_progress": scalar("SELECT COUNT(*) AS n FROM watch_progress WHERE status = 'in_progress'"),
            }

    # -- email + password accounts --------------------------------------
    def get_account_by_email(self, email: str) -> Optional[Dict]:
        """Case-insensitive lookup by email."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM accounts WHERE LOWER(email) = LOWER(%s)", (email,)
            ).fetchone()
            return dict(row) if row else None

    def create_email_account(
        self, email: str, password_hash: str, label: Optional[str] = None
    ) -> Dict:
        """Create an email+password account (unverified). Raises
        psycopg.errors.UniqueViolation if the email is already taken."""
        with self._connect() as conn:
            row = conn.execute(
                """
                INSERT INTO accounts (email, password_hash, label, email_verified, created_at)
                VALUES (%s, %s, %s, FALSE, %s) RETURNING user_id
                """,
                (email, password_hash, label, _iso(_now())),
            ).fetchone()
            user_id = row["user_id"]
        return self.get_account(user_id)

    def set_password(self, user_id: int, password_hash: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET password_hash = %s WHERE user_id = %s",
                (password_hash, user_id),
            )

    def set_email_verified(self, user_id: int, verified: bool = True) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE accounts SET email_verified = %s WHERE user_id = %s",
                (verified, user_id),
            )

    # -- email tokens (verification / password reset) -------------------
    def create_email_token(self, user_id: int, purpose: str, ttl: timedelta) -> str:
        """Issue a single-use token for ``purpose`` ('verify' | 'reset') and return
        it raw. Earlier tokens of the same purpose are dropped so only the newest
        link works."""
        raw = secrets.token_urlsafe(32)
        expires = _now() + ttl
        with self._connect() as conn:
            conn.execute(
                "DELETE FROM email_tokens WHERE user_id = %s AND purpose = %s",
                (user_id, purpose),
            )
            conn.execute(
                "INSERT INTO email_tokens (token_hash, user_id, purpose, created_at, expires_at)"
                " VALUES (%s, %s, %s, %s, %s)",
                (_hash_token(raw), user_id, purpose, _iso(_now()), _iso(expires)),
            )
        return raw

    def consume_email_token(self, raw_token: str, purpose: str) -> Optional[int]:
        """Atomically validate and delete a token; user_id on success, else None.
        The DELETE rowcount gates consumption, so a link can't be replayed."""
        if not raw_token:
            return None
        token_hash = _hash_token(raw_token)
        with self._connect() as conn:
            row = conn.execute(
                "SELECT user_id, purpose, expires_at FROM email_tokens WHERE token_hash = %s",
                (token_hash,),
            ).fetchone()
            if row is None:
                return None
            cur = conn.execute(
                "DELETE FROM email_tokens WHERE token_hash = %s", (token_hash,)
            )
            if cur.rowcount == 0 or row["purpose"] != purpose:
                return None
            try:
                if datetime.fromisoformat(row["expires_at"]) <= _now():
                    return None
            except ValueError:
                return None
            return row["user_id"]

    def revoke_user_sessions(self, user_id: int) -> None:
        """Drop every session, so a leaked one can't outlive a password reset."""
        with self._connect() as conn:
            conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    # -- single-use invite tokens (minted by the Discord bot) -----------
    def create_invite_token(
        self, created_by: Optional[str] = None, ttl: Optional[timedelta] = None
    ) -> str:
        """Mint a single-use invite code. ``created_by`` is the Discord user id that
        requested it; a ``ttl`` of None never expires (still single-use)."""
        code = secrets.token_hex(8)  # unguessable but easy to paste
        expires = _iso(_now() + ttl) if ttl else None
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO invite_tokens (code, created_by, created_at, expires_at)"
                " VALUES (%s, %s, %s, %s)",
                (code, created_by, _iso(_now()), expires),
            )
        return code

    def invite_token_is_available(self, code: str) -> bool:
        """Read-only pre-check for a clean error message. Consumption is gated
        authoritatively and race-safely by consume_invite_token."""
        if not code:
            return False
        with self._connect() as conn:
            row = conn.execute(
                "SELECT expires_at, used_at FROM invite_tokens WHERE code = %s", (code,)
            ).fetchone()
        if row is None or row["used_at"] is not None:
            return False
        if row["expires_at"]:
            try:
                if datetime.fromisoformat(row["expires_at"]) <= _now():
                    return False
            except ValueError:
                return False
        return True

    def consume_invite_token(self, code: str, used_by: Optional[str] = None) -> bool:
        """Burn a single-use invite token; True only if it existed, was unused and
        had not expired. The ``used_at IS NULL`` guard makes it race-safe: two
        concurrent signups contend on the row and only one UPDATE matches."""
        if not code:
            return False
        now = _iso(_now())
        with self._connect() as conn:
            cur = conn.execute(
                """
                UPDATE invite_tokens
                   SET used_at = %s, used_by = %s
                 WHERE code = %s
                   AND used_at IS NULL
                   AND (expires_at IS NULL OR expires_at > %s)
                """,
                (now, used_by, code, now),
            )
            return cur.rowcount > 0

    def list_invite_tokens(self, include_used: bool = False, limit: int = 50) -> List[Dict]:
        """Newest invite tokens; unused only unless ``include_used``."""
        with self._connect() as conn:
            if include_used:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM invite_tokens WHERE used_at IS NULL"
                    " ORDER BY created_at DESC LIMIT %s",
                    (limit,),
                ).fetchall()
            return [dict(r) for r in rows]

    def revoke_invite_token(self, code: str) -> bool:
        """Delete an unused invite token. False if unknown or already used, since
        used rows stay as a ledger."""
        if not code:
            return False
        with self._connect() as conn:
            cur = conn.execute(
                "DELETE FROM invite_tokens WHERE code = %s AND used_at IS NULL", (code,)
            )
            return cur.rowcount > 0

    # -- challenges (one-time login nonces) -----------------------------
    def create_challenge(self, public_key: str, purpose: str) -> Tuple[str, str]:
        challenge = secrets.token_urlsafe(32)
        expires = _now() + CHALLENGE_TTL
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO challenges (challenge, public_key, purpose, expires_at) VALUES (%s, %s, %s, %s)",
                (challenge, public_key, purpose, _iso(expires)),
            )
        return challenge, _iso(expires)

    def consume_challenge(self, challenge: str, public_key: str, purpose: str) -> bool:
        """Validate and delete a challenge; true only if it matched and was fresh."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT public_key, purpose, expires_at FROM challenges WHERE challenge = %s",
                (challenge,),
            ).fetchone()
            if row is None:
                return False
            # Delete unconditionally and gate on rowcount: two concurrent requests
            # can both SELECT the row, but only the one whose DELETE removes it may
            # consume it, so a captured signature can't be replayed in parallel.
            cur = conn.execute("DELETE FROM challenges WHERE challenge = %s", (challenge,))
            if cur.rowcount == 0:
                return False
            if row["public_key"] != public_key or row["purpose"] != purpose:
                return False
            try:
                expires = datetime.fromisoformat(row["expires_at"])
            except ValueError:
                return False
            return expires > _now()

    # -- sessions -------------------------------------------------------
    def create_session(
        self, user_id: int,
        user_agent: Optional[str] = None, ip: Optional[str] = None,
    ) -> Tuple[str, str]:
        """Issue a session as (raw_token, expires_at_iso). Only the hash is stored.

        The device columns are what let their owner recognise a session later;
        they are optional so the callers that have no request context still work.
        """
        raw = secrets.token_urlsafe(32)
        now = _now()
        expires = now + SESSION_TTL
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO sessions (token_hash, user_id, created_at, expires_at,
                                      user_agent, ip, last_seen_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (_hash_token(raw), user_id, _iso(now), _iso(expires),
                 (user_agent or None), (ip or None), _iso(now)),
            )
        return raw, _iso(expires)

    def get_user_by_session(self, raw_token: str) -> Optional[Dict]:
        if not raw_token:
            return None
        with self._connect() as conn:
            row = conn.execute(
                """
                SELECT a.* , s.expires_at AS session_expires_at
                FROM sessions s JOIN accounts a ON a.user_id = s.user_id
                WHERE s.token_hash = %s
                """,
                (_hash_token(raw_token),),
            ).fetchone()
            if row is None:
                return None
            try:
                if datetime.fromisoformat(row["session_expires_at"]) <= _now():
                    conn.execute(
                        "DELETE FROM sessions WHERE token_hash = %s", (_hash_token(raw_token),)
                    )
                    return None
            except ValueError:
                return None
            return dict(row)

    def delete_session(self, raw_token: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "DELETE FROM sessions WHERE token_hash = %s", (_hash_token(raw_token),)
            )

    def validate_and_touch_session(self, raw_token: str) -> bool:
        """True iff the token names a live session. On success, stamp last_seen_at.

        Mirrors ApiKeyStore.validate_and_touch: called only on a cache miss in the
        login wall, so the write happens at most once per session per cache-TTL
        rather than once per request. One statement, so recording the use costs
        nothing beyond the check that was happening anyway."""
        if not raw_token:
            return False
        now = _iso(_now())
        with self._connect() as conn:
            cur = conn.execute(
                "UPDATE sessions SET last_seen_at = %s"
                " WHERE token_hash = %s AND expires_at > %s",
                (now, _hash_token(raw_token), now),
            )
            return cur.rowcount > 0

    def list_sessions(self, user_id: int, current_token: Optional[str] = None) -> List[Dict]:
        """The account's live sessions, newest first, with the caller's flagged.

        Deliberately does not return ``token_hash`` under any name: the public id
        is derived here so a route handler cannot leak the hash by forwarding a
        row it did not inspect."""
        current_hash = _hash_token(current_token) if current_token else None
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT token_hash, created_at, expires_at, user_agent, ip, last_seen_at
                FROM sessions
                WHERE user_id = %s AND expires_at > %s
                ORDER BY created_at DESC
                """,
                (user_id, _iso(_now())),
            ).fetchall()
        return [
            {
                "id": _public_session_id(r["token_hash"]),
                "created_at": r["created_at"],
                "expires_at": r["expires_at"],
                "last_seen_at": r["last_seen_at"],
                "user_agent": r["user_agent"],
                "ip": r["ip"],
                "current": current_hash is not None and r["token_hash"] == current_hash,
            }
            for r in rows
        ]

    def revoke_session(self, user_id: int, session_id: str) -> bool:
        """Revoke one session of this account by its public id.

        The public id is a one-way derivation of the primary key, so it cannot be
        turned back into a WHERE clause. Matching in Python over the account's own
        handful of rows is the honest way to do it, and it keeps the scan bound to
        one user_id so the id is never an oracle for another account's session."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT token_hash FROM sessions WHERE user_id = %s", (user_id,)
            ).fetchall()
            for r in rows:
                if _public_session_id(r["token_hash"]) == session_id:
                    conn.execute(
                        "DELETE FROM sessions WHERE token_hash = %s", (r["token_hash"],)
                    )
                    return True
        return False

    def revoke_other_sessions(self, user_id: int, current_token: Optional[str]) -> int:
        """Sign out everywhere except the caller. Returns how many were dropped."""
        with self._connect() as conn:
            if current_token:
                cur = conn.execute(
                    "DELETE FROM sessions WHERE user_id = %s AND token_hash <> %s",
                    (user_id, _hash_token(current_token)),
                )
            else:
                cur = conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))
            return cur.rowcount

    # -- favorites / watchlists -----------------------------------------
    # A favorite is a row in a named list. 'favorites' is the default; any other
    # name is a custom watchlist. The same show may live in several lists.
    def upsert_favorite(self, user_id: int, fav: Dict, list_name: str = "favorites") -> Dict:
        with self._connect() as conn:
            # Soft cap on new keys only; updates always pass. Same transaction as
            # the insert, so a small concurrent overshoot is possible and harmless.
            exists = conn.execute(
                "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_FAVORITES_PER_USER:
                    raise QuotaExceeded(f"favorites limit ({MAX_FAVORITES_PER_USER}) reached")
            conn.execute(
                _FAVORITE_UPSERT,
                {"user_id": user_id, "list_name": list_name, "added_at": _iso(_now()), **fav},
            )
            row = conn.execute(
                "SELECT * FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                (user_id, fav["item_key"], list_name),
            ).fetchone()
            return dict(row)

    def list_favorites(self, user_id: int, list_name: Optional[str] = None) -> List[Dict]:
        """Rows in one list, or every list (newest first) when ``list_name`` is None."""
        with self._connect() as conn:
            if list_name is None:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s ORDER BY added_at DESC",
                    (user_id,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM favorites WHERE user_id = %s AND list_name = %s "
                    "ORDER BY added_at DESC",
                    (user_id, list_name),
                ).fetchall()
            return [dict(r) for r in rows]

    def list_watchlists(self, user_id: int) -> List[Dict]:
        """Distinct list names with each list's item count."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT list_name, COUNT(*) AS count FROM favorites WHERE user_id = %s "
                "GROUP BY list_name ORDER BY list_name",
                (user_id,),
            ).fetchall()
            return [dict(r) for r in rows]

    def bulk_upsert_favorites(
        self, user_id: int, items: List[Tuple[str, Dict]], replace: bool = False
    ) -> Dict:
        """Insert/update many favorites in one transaction, for import.

        ``items`` is a list of ``(list_name, fav)`` pairs. New keys are inserted
        only while the per-account cap has room; existing keys always update.
        ``replace`` clears every list first, in the same transaction, so a failed
        import never leaves the account empty. Returns ``{"imported", "skipped_quota"}``."""
        imported = 0
        skipped_quota = 0
        now = _iso(_now())
        with self._connect() as conn:
            if replace:
                conn.execute("DELETE FROM favorites WHERE user_id = %s", (user_id,))
            count = conn.execute(
                "SELECT COUNT(*) AS n FROM favorites WHERE user_id = %s", (user_id,)
            ).fetchone()["n"]
            for list_name, fav in items:
                exists = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, fav["item_key"], list_name),
                ).fetchone()
                if exists is None:
                    if count >= MAX_FAVORITES_PER_USER:
                        skipped_quota += 1
                        continue
                    count += 1
                conn.execute(
                    _FAVORITE_UPSERT,
                    {"user_id": user_id, "list_name": list_name, "added_at": now, **fav},
                )
                imported += 1
        return {"imported": imported, "skipped_quota": skipped_quota}

    def remove_favorite(
        self, user_id: int, item_key: str, list_name: Optional[str] = None
    ) -> bool:
        """Remove a show from one list, or from every list when ``list_name`` is None."""
        with self._connect() as conn:
            if list_name is None:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s",
                    (user_id, item_key),
                )
            else:
                cur = conn.execute(
                    "DELETE FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, item_key, list_name),
                )
            return cur.rowcount > 0

    def is_favorite(
        self, user_id: int, item_key: str, list_name: Optional[str] = None
    ) -> bool:
        with self._connect() as conn:
            if list_name is None:
                row = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s",
                    (user_id, item_key),
                ).fetchone()
            else:
                row = conn.execute(
                    "SELECT 1 FROM favorites WHERE user_id = %s AND item_key = %s AND list_name = %s",
                    (user_id, item_key, list_name),
                ).fetchone()
            return row is not None

    # -- watch progress -------------------------------------------------
    def upsert_progress(self, user_id: int, prog: Dict) -> Dict:
        with self._connect() as conn:
            # Soft cap on new keys only, so progress saves keep working at the cap.
            exists = conn.execute(
                "SELECT 1 FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            if exists is None:
                count = conn.execute(
                    "SELECT COUNT(*) AS n FROM watch_progress WHERE user_id = %s", (user_id,)
                ).fetchone()["n"]
                if count >= MAX_PROGRESS_PER_USER:
                    raise QuotaExceeded(f"progress limit ({MAX_PROGRESS_PER_USER}) reached")
            conn.execute(
                """
                INSERT INTO watch_progress
                    (user_id, item_key, tmdb_id, anilist_id, season_number,
                     episode_number, position_seconds, duration_seconds, status,
                     title, poster, media_type, local_id, updated_at)
                VALUES (%(user_id)s, %(item_key)s, %(tmdb_id)s, %(anilist_id)s, %(season_number)s,
                        %(episode_number)s, %(position_seconds)s, %(duration_seconds)s, %(status)s,
                        %(title)s, %(poster)s, %(media_type)s, %(local_id)s, %(updated_at)s)
                ON CONFLICT(user_id, item_key) DO UPDATE SET
                    tmdb_id=excluded.tmdb_id, anilist_id=excluded.anilist_id,
                    season_number=excluded.season_number, episode_number=excluded.episode_number,
                    position_seconds=excluded.position_seconds, duration_seconds=excluded.duration_seconds,
                    status=excluded.status, title=excluded.title, poster=excluded.poster,
                    media_type=excluded.media_type, local_id=excluded.local_id, updated_at=excluded.updated_at
                """,
                {"user_id": user_id, "updated_at": _iso(_now()),
                 "media_type": None, "local_id": None, **prog},
            )
            # The history half of the same save. watch_progress is keyed
            # (user_id, item_key) and overwritten on a timer, so it cannot say
            # when anything was watched; this row can. Same connection and same
            # threadpool call as the upsert above on purpose: POST
            # /account/progress fires every 30s for every viewer in every
            # playback session, and a second round trip there is not free.
            conn.execute(
                """
                INSERT INTO watch_events
                    (user_id, item_key, watched_on, anilist_id, tmdb_id, media_type, title, seconds)
                VALUES (%(user_id)s, %(item_key)s, (now() AT TIME ZONE 'utc')::date,
                        %(anilist_id)s, %(tmdb_id)s, %(media_type)s, %(title)s, %(position_seconds)s)
                ON CONFLICT (user_id, item_key, watched_on) DO UPDATE SET
                    -- The furthest point reached that day. A rewatch restarts at
                    -- zero and climbs again, so taking the max is the only answer
                    -- that does not shrink as you keep watching.
                    seconds = GREATEST(COALESCE(watch_events.seconds, 0),
                                       COALESCE(excluded.seconds, 0)),
                    title = COALESCE(excluded.title, watch_events.title)
                """,
                {"user_id": user_id, "item_key": prog["item_key"],
                 "anilist_id": prog.get("anilist_id"), "tmdb_id": prog.get("tmdb_id"),
                 "media_type": prog.get("media_type"), "title": prog.get("title"),
                 "position_seconds": prog.get("position_seconds")},
            )

            row = conn.execute(
                "SELECT * FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, prog["item_key"]),
            ).fetchone()
            return dict(row)

    def list_progress(self, user_id: int, status: Optional[str] = None) -> List[Dict]:
        with self._connect() as conn:
            if status:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s AND status = %s ORDER BY updated_at DESC",
                    (user_id, status),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM watch_progress WHERE user_id = %s ORDER BY updated_at DESC",
                    (user_id,),
                ).fetchall()
            return [dict(r) for r in rows]

    def remove_progress(self, user_id: int, item_key: str) -> bool:
        with self._connect() as conn:
            cur = conn.execute(
                "DELETE FROM watch_progress WHERE user_id = %s AND item_key = %s",
                (user_id, item_key),
            )
            return cur.rowcount > 0

    # -- maintenance ----------------------------------------------------
    def purge_expired(self) -> None:
        """Drop expired sessions, challenges, email tokens and old watch events."""
        now = _iso(_now())
        with self._connect() as conn:
            conn.execute("DELETE FROM sessions WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM challenges WHERE expires_at <= %s", (now,))
            conn.execute("DELETE FROM email_tokens WHERE expires_at <= %s", (now,))
            # init_db() calls this, and init_db() runs before the migration
            # runner by design, so on the first boot after 006 the table does not
            # exist yet. Nothing to prune then, and asking first is cheaper than
            # aborting the transaction this method shares.
            if conn.execute("SELECT to_regclass('public.watch_events') AS t").fetchone()["t"]:
                conn.execute(
                    "DELETE FROM watch_events WHERE watched_on < %s",
                    ((_now() - timedelta(days=WATCH_EVENTS_RETENTION_DAYS)).date(),),
                )
