"""
PostgreSQL store for the admin-managed local media sources.

Each row is one directory the operator has registered from the Admin Dashboard
(a NAS share or a Docker bind-mount, e.g. ``-v /movies:/crimson/movies1`` →
register ``/crimson/movies1``). The "Local" scraper scans every *enabled* root
for matching files, and the ``/local_proxy`` route re-validates against the same
enabled set on every request, so disabling/removing a source instantly stops
playback.

Mirrors account_engine.db's pooled, synchronous psycopg style: methods are plain
psycopg calls borrowing from the shared pool (db_pool), called from api.py's async
handlers via ``run_in_threadpool``. Volumes are tiny (a handful of rows).
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import List, Optional

from db_pool import get_connection, lock_schema_init

_COLS = "id, label, path, enabled, created_at"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class LocalSourceStore:
    """Thin data layer for the ``local_media_sources`` table."""

    # The enabled-roots list is read on every scrape AND every /local_proxy
    # request, so it's cached process-wide for a few seconds. Kept at class level
    # so the cache is shared no matter which instance (scraper/resolver/route/
    # admin) reads it; any write invalidates it via _bump().
    _roots_cache: Optional[List[str]] = None
    _roots_cache_at: float = 0.0
    _ROOTS_TTL = 5.0

    # -- schema ---------------------------------------------------------------
    def init_db(self) -> None:
        """Create the schema (idempotent)."""
        with get_connection() as conn:
            lock_schema_init(conn)  # serialize DDL across replicas (see db_pool)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS local_media_sources (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label      TEXT NOT NULL,
                    path       TEXT NOT NULL UNIQUE,
                    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TEXT NOT NULL
                );
                """
            )

    # -- reads ----------------------------------------------------------------
    def list_sources(self) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM local_media_sources ORDER BY created_at, id"
            ).fetchall()

    def get_source(self, source_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM local_media_sources WHERE id = %s", (source_id,)
            ).fetchone()

    def enabled_roots(self) -> List[str]:
        """Paths of all enabled sources (cached briefly; see class docstring)."""
        now = time.monotonic()
        cached = LocalSourceStore._roots_cache
        if cached is not None and (now - LocalSourceStore._roots_cache_at) < LocalSourceStore._ROOTS_TTL:
            return cached
        try:
            with get_connection() as conn:
                rows = conn.execute(
                    "SELECT path FROM local_media_sources WHERE enabled = TRUE"
                ).fetchall()
            roots = [r["path"] for r in rows]
        except Exception:
            # DB hiccup: serve the last known roots rather than 500 a playback.
            roots = cached or []
        LocalSourceStore._roots_cache = roots
        LocalSourceStore._roots_cache_at = now
        return roots

    # -- writes ---------------------------------------------------------------
    def add_source(self, label: str, path: str) -> dict:
        with get_connection() as conn:
            row = conn.execute(
                f"""
                INSERT INTO local_media_sources (label, path, enabled, created_at)
                VALUES (%s, %s, TRUE, %s)
                RETURNING {_COLS}
                """,
                (label, path, _now_iso()),
            ).fetchone()
        self._bump()
        return row

    def update_source(
        self, source_id: int, label: Optional[str] = None, enabled: Optional[bool] = None
    ) -> Optional[dict]:
        sets, vals = [], []
        if label is not None:
            sets.append("label = %s")
            vals.append(label)
        if enabled is not None:
            sets.append("enabled = %s")
            vals.append(enabled)
        if not sets:
            return self.get_source(source_id)
        vals.append(source_id)
        with get_connection() as conn:
            row = conn.execute(
                f"UPDATE local_media_sources SET {', '.join(sets)} WHERE id = %s RETURNING {_COLS}",
                tuple(vals),
            ).fetchone()
        self._bump()
        return row

    def delete_source(self, source_id: int) -> bool:
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM local_media_sources WHERE id = %s RETURNING id", (source_id,)
            ).fetchone()
        self._bump()
        return row is not None

    # -- cache ----------------------------------------------------------------
    @staticmethod
    def _bump() -> None:
        """Invalidate the enabled-roots cache after any write."""
        LocalSourceStore._roots_cache = None
        LocalSourceStore._roots_cache_at = 0.0
