"""Postgres store for the admin-registered Local source roots (``local_media_sources``).

Each row is a directory, typically a Docker bind-mount, with three switches:
``enabled`` (served at all), ``encoding`` (non-web containers are transcoded to
HLS) and ``download_enabled`` (the downloader may write into it).
"""

from __future__ import annotations

import time
from typing import List, Optional

from core.db_pool import get_connection, lock_schema_init
from core.clock import utc_now_iso

_COLS = "id, label, path, enabled, encoding, download_enabled, created_at"


class LocalSourceStore:
    # Read on every scrape and every /local_proxy and /local_hls request, so held
    # for a few seconds. Writes on this replica invalidate at once.
    _roots_cache: Optional[List[dict]] = None
    _roots_cache_at: float = 0.0
    _ROOTS_TTL = 5.0

    def init_db(self) -> None:
        with get_connection() as conn:
            lock_schema_init(conn)
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS local_media_sources (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    label      TEXT NOT NULL,
                    path       TEXT NOT NULL UNIQUE,
                    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
                    encoding   BOOLEAN NOT NULL DEFAULT FALSE,
                    download_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TEXT NOT NULL
                );
                """
            )

    def list_sources(self) -> List[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM local_media_sources ORDER BY created_at, id"
            ).fetchall()

    def get_source(self, source_id: int) -> Optional[dict]:
        with get_connection() as conn:
            return conn.execute(
                f"SELECT {_COLS} FROM local_media_sources WHERE id = %s", (source_id,)
            ).fetchone()

    def enabled_roots_config(self) -> List[dict]:
        """``{"id", "path", "encoding", "download_enabled", "label"}`` per enabled
        source, so one cached read answers every per-request question."""
        now = time.monotonic()
        cached = LocalSourceStore._roots_cache
        if cached is not None and (now - LocalSourceStore._roots_cache_at) < LocalSourceStore._ROOTS_TTL:
            return cached
        try:
            with get_connection() as conn:
                rows = conn.execute(
                    "SELECT id, path, encoding, download_enabled, label "
                    "FROM local_media_sources WHERE enabled = TRUE ORDER BY created_at, id"
                ).fetchall()
            config = [
                {
                    "id": r["id"],
                    "path": r["path"],
                    "encoding": bool(r["encoding"]),
                    "download_enabled": bool(r["download_enabled"]),
                    "label": r["label"],
                }
                for r in rows
            ]
        except Exception:
            # Serve the last known config rather than fail a playback on a DB hiccup.
            config = cached or []
        LocalSourceStore._roots_cache = config
        LocalSourceStore._roots_cache_at = now
        return config

    def enabled_roots(self) -> List[str]:
        return [r["path"] for r in self.enabled_roots_config()]

    def download_roots_config(self) -> List[dict]:
        """In registration order, the order the downloader tries them."""
        return [r for r in self.enabled_roots_config() if r.get("download_enabled")]

    def add_source(
        self, label: str, path: str, encoding: bool = False, download_enabled: bool = False
    ) -> dict:
        with get_connection() as conn:
            row = conn.execute(
                f"""
                INSERT INTO local_media_sources (label, path, enabled, encoding, download_enabled, created_at)
                VALUES (%s, %s, TRUE, %s, %s, %s)
                RETURNING {_COLS}
                """,
                (label, path, encoding, download_enabled, utc_now_iso()),
            ).fetchone()
        self._bump()
        return row

    def update_source(
        self,
        source_id: int,
        label: Optional[str] = None,
        enabled: Optional[bool] = None,
        encoding: Optional[bool] = None,
        download_enabled: Optional[bool] = None,
    ) -> Optional[dict]:
        sets: list[str] = []
        vals: list = []
        if label is not None:
            sets.append("label = %s")
            vals.append(label)
        if enabled is not None:
            sets.append("enabled = %s")
            vals.append(enabled)
        if encoding is not None:
            sets.append("encoding = %s")
            vals.append(encoding)
        if download_enabled is not None:
            sets.append("download_enabled = %s")
            vals.append(download_enabled)
        if not sets:
            return self.get_source(source_id)
        vals.append(source_id)
        with get_connection() as conn:
            row = conn.execute(
                f"UPDATE local_media_sources SET {', '.join(sets)} WHERE id = %s RETURNING {_COLS}",
                tuple(vals),
            ).fetchone()
        self._bump()
        return row

    def delete_source(self, source_id: int) -> bool:
        with get_connection() as conn:
            row = conn.execute(
                "DELETE FROM local_media_sources WHERE id = %s RETURNING id", (source_id,)
            ).fetchone()
        self._bump()
        return row is not None

    @staticmethod
    def _bump() -> None:
        LocalSourceStore._roots_cache = None
        LocalSourceStore._roots_cache_at = 0.0


store = LocalSourceStore()
