"""
One-shot migration: copy user data from the legacy SQLite ``accounts.db`` into
the new PostgreSQL database.

Only the account data needs migrating. The TMDB<->AniList mapping + api_cache
(the old ``anime_mappings.db``) is disposable — the app rebuilds it from Fribb
on first boot — so it is intentionally NOT touched here.

What moves: accounts, sessions, favorites, watch_progress. Challenges are
ephemeral (5-minute TTL) and deliberately skipped. Existing ``user_id`` values
are preserved (the new column is ``GENERATED BY DEFAULT AS IDENTITY``, so explicit
ids are allowed) which keeps every favorite/progress/session FK pointing at the
right account; afterwards the identity sequence is bumped past the highest id so
the next freshly-registered account does not collide.

The copy is idempotent (``ON CONFLICT DO NOTHING``): safe to re-run, and safe to
run against a database that already has some rows.

Usage
-----
    # target is read from DATABASE_URL / POSTGRES_* (same as the app, see db_pool)
    DATABASE_URL=postgresql://crimson:crimson@localhost:5432/crimson \
        python migrate_sqlite_to_postgres.py path/to/accounts.db

If no path is given it falls back to $ACCOUNTS_DB, then ./accounts.db.
"""

from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

# This script now lives in scripts/; put the repo root on sys.path so it can still
# be run directly (``python scripts/migrate_sqlite_to_postgres.py``) and import the
# app packages (account_engine, core).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

# Tables to copy, in FK-safe order (parents before children).
TABLES = ["accounts", "sessions", "favorites", "watch_progress"]


def _resolve_sqlite_path(argv: list[str]) -> str:
    if len(argv) > 1:
        return argv[1]
    return os.getenv("ACCOUNTS_DB", "accounts.db")


def _read_table(sconn: sqlite3.Connection, table: str):
    """Return (columns, rows) for a table, or (None, []) if it doesn't exist."""
    exists = sconn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    if not exists:
        return None, []
    cur = sconn.execute(f"SELECT * FROM {table}")
    columns = [d[0] for d in cur.description]
    rows = [tuple(r) for r in cur.fetchall()]
    return columns, rows


def main() -> int:
    load_dotenv()

    sqlite_path = _resolve_sqlite_path(sys.argv)
    if not os.path.exists(sqlite_path):
        print(f"[migrate] SQLite file not found: {sqlite_path}", file=sys.stderr)
        return 1

    # Import after load_dotenv so the pool reads the right DATABASE_URL, and only
    # now (so a missing psycopg surfaces a clear error rather than at top import).
    from account_engine.db import AccountStore
    from core import db_pool

    print(f"[migrate] Source SQLite : {sqlite_path}")
    print(f"[migrate] Target Postgres: {db_pool._dsn().rsplit('@', 1)[-1]}")

    # Ensure the destination schema exists (idempotent).
    AccountStore().init_db()

    sconn = sqlite3.connect(sqlite_path)
    sconn.row_factory = sqlite3.Row
    try:
        with db_pool.get_connection() as pconn:
            pcur = pconn.cursor()
            for table in TABLES:
                columns, rows = _read_table(sconn, table)
                if columns is None:
                    print(f"[migrate] {table:>15}: not present in source, skipped")
                    continue
                if not rows:
                    print(f"[migrate] {table:>15}: 0 rows")
                    continue
                collist = ", ".join(columns)
                placeholders = ", ".join(["%s"] * len(columns))
                pcur.executemany(
                    f"INSERT INTO {table} ({collist}) VALUES ({placeholders}) "
                    f"ON CONFLICT DO NOTHING",
                    rows,
                )
                print(f"[migrate] {table:>15}: {len(rows)} rows copied")

            # Bump the accounts identity sequence past the highest migrated id so
            # the next INSERT without an explicit user_id doesn't collide.
            row = pcur.execute("SELECT MAX(user_id) AS m FROM accounts").fetchone()
            max_id = row["m"]
            if max_id is not None:
                pcur.execute(
                    "SELECT setval(pg_get_serial_sequence('accounts', 'user_id'), %s, true)",
                    (max_id,),
                )
                print(f"[migrate] accounts identity sequence set to {max_id} (next id = {max_id + 1})")
    finally:
        sconn.close()
        db_pool.close_pool()

    print("[migrate] Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
